package desktop

import (
	"encoding/base64"
	"encoding/json"
	"strconv"
	"strings"
)

type Template struct {
	Tool            string            `json:"tool"`
	Label           string            `json:"label"`
	ServerAddress   string            `json:"server_address"`
	Endpoint        string            `json:"endpoint"`
	AuthScheme      string            `json:"auth_scheme"`
	ModelFormat     string            `json:"model_format"`
	Env             map[string]string `json:"env"`
	DefaultProvider string            `json:"default_provider"`
}
type ImportInput struct {
	Target      string `json:"target"`
	Tool        string `json:"tool"`
	TokenID     int64  `json:"token_id"`
	Name        string `json:"name"`
	Model       string `json:"model"`
	HaikuModel  string `json:"haiku_model"`
	SonnetModel string `json:"sonnet_model"`
	OpusModel   string `json:"opus_model"`
	Enabled     *bool  `json:"enabled"`
}
type ImportPayload struct {
	Tool         string `json:"tool"`
	Name         string `json:"name"`
	Homepage     string `json:"homepage"`
	Endpoint     string `json:"endpoint"`
	APIKey       string `json:"apiKey"`
	Model        string `json:"model,omitempty"`
	HaikuModel   string `json:"haikuModel,omitempty"`
	SonnetModel  string `json:"sonnetModel,omitempty"`
	OpusModel    string `json:"opusModel,omitempty"`
	Enabled      bool   `json:"enabled"`
	Config       string `json:"config"`
	ConfigFormat string `json:"configFormat"`
	Icon         string `json:"icon,omitempty"`
	Notes        string `json:"notes,omitempty"`
}

var tools = []string{"codex", "claude", "gemini", "opencode", "openclaw", "hermes"}

func normalizeTool(raw string) string {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case "codex":
		return "codex"
	case "claude", "claude-code":
		return "claude"
	case "gemini", "gemini-cli":
		return "gemini"
	case "opencode", "open-code":
		return "opencode"
	case "openclaw", "open-claw":
		return "openclaw"
	case "hermes", "hermes-agent":
		return "hermes"
	default:
		return ""
	}
}
func (s *Service) template(raw string) (Template, error) {
	tool := normalizeTool(raw)
	if tool == "" {
		return Template{}, ErrInvalid
	}
	out := Template{Tool: tool, ServerAddress: s.cfg.PublicURL, Endpoint: s.cfg.PublicURL + "/v1", DefaultProvider: "codego", ModelFormat: "openai-compatible", AuthScheme: "openai-compatible-api-key", Env: map[string]string{"OPENAI_BASE_URL": s.cfg.PublicURL + "/v1"}}
	switch tool {
	case "codex":
		out.Label = "Codex"
		out.ModelFormat = "responses"
		out.AuthScheme = "openai-api-key"
		out.Env["OPENAI_API_BASE"] = out.Endpoint
	case "claude":
		out.Label = "Claude Code"
		out.Endpoint = s.cfg.PublicURL
		out.ModelFormat = "anthropic"
		out.AuthScheme = "anthropic-auth-token"
		out.Env = map[string]string{"ANTHROPIC_BASE_URL": out.Endpoint}
	case "gemini":
		out.Label = "Gemini CLI"
		out.Endpoint = s.cfg.PublicURL
		out.ModelFormat = "gemini"
		out.AuthScheme = "google-api-key-compatible"
		out.Env = map[string]string{"GOOGLE_API_BASE": out.Endpoint}
	case "opencode":
		out.Label = "OpenCode"
	case "openclaw":
		out.Label = "OpenClaw"
	case "hermes":
		out.Label = "Hermes"
		out.ModelFormat = "chat-completions"
	}
	return out, nil
}

func (s *Service) buildConfig(raw string, in ImportInput) (ImportPayload, error) {
	t, err := s.template(in.Tool)
	if err != nil {
		return ImportPayload{}, err
	}
	if len(in.Name) > 100 || len(in.Model) > 256 || len(in.HaikuModel) > 256 || len(in.SonnetModel) > 256 || len(in.OpusModel) > 256 {
		return ImportPayload{}, ErrInvalid
	}
	out := ImportPayload{Tool: t.Tool, Name: strings.TrimSpace(in.Name), Homepage: t.ServerAddress, Endpoint: t.Endpoint, APIKey: raw, Model: strings.TrimSpace(in.Model), HaikuModel: strings.TrimSpace(in.HaikuModel), SonnetModel: strings.TrimSpace(in.SonnetModel), OpusModel: strings.TrimSpace(in.OpusModel), Enabled: in.Enabled == nil || *in.Enabled, ConfigFormat: "json", Icon: "codego", Notes: "Generated by Code Go Desktop import"}
	if out.Name == "" {
		label := t.Label
		if t.Tool == "claude" {
			label = "Claude"
		}
		if t.Tool == "gemini" {
			label = "Gemini"
		}
		out.Name = "Code Go " + label
	}
	model := in.Model
	if model == "" {
		model = "gpt-5.5"
	}
	var body any
	switch t.Tool {
	case "claude":
		env := map[string]string{"ANTHROPIC_BASE_URL": t.Endpoint, "ANTHROPIC_AUTH_TOKEN": raw}
		for key, value := range map[string]string{"ANTHROPIC_MODEL": in.Model, "ANTHROPIC_DEFAULT_HAIKU_MODEL": in.HaikuModel, "ANTHROPIC_DEFAULT_SONNET_MODEL": in.SonnetModel, "ANTHROPIC_DEFAULT_OPUS_MODEL": in.OpusModel} {
			if value != "" {
				env[key] = value
			}
		}
		body = map[string]any{"env": env}
	case "gemini":
		env := map[string]string{"GEMINI_API_KEY": raw, "GOOGLE_GEMINI_BASE_URL": t.Endpoint}
		if in.Model != "" {
			env["GEMINI_MODEL"] = in.Model
		}
		body = env
	case "codex":
		body = map[string]any{"auth": map[string]string{"OPENAI_API_KEY": raw}, "config": "model_provider = \"custom\"\nmodel = " + strconv.Quote(model) + "\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.custom]\nname = \"Code Go\"\nbase_url = " + strconv.Quote(t.Endpoint) + "\nwire_api = \"responses\"\nrequires_openai_auth = true\n"}
	case "opencode":
		body = map[string]any{"npm": "@ai-sdk/openai-compatible", "name": out.Name, "options": map[string]any{"baseURL": t.Endpoint, "apiKey": raw, "setCacheKey": true}, "models": map[string]any{model: map[string]string{"name": model}}}
	case "openclaw":
		body = map[string]any{"baseUrl": t.Endpoint, "apiKey": raw, "api": "openai-completions", "models": []map[string]string{{"id": model, "name": model}}}
	case "hermes":
		body = map[string]any{"name": out.Name, "base_url": t.Endpoint, "api_key": raw, "api_mode": "chat_completions", "models": []map[string]string{{"id": model, "name": model}}}
	}
	b, err := json.Marshal(body)
	if err != nil {
		return out, err
	}
	out.Config = base64.StdEncoding.EncodeToString(b)
	return out, nil
}
