package gateway_test

import (
	"testing"

	"github.com/sh2001sh/new-api/v3/internal/gateway"
	"github.com/sh2001sh/new-api/v3/internal/gateway/providers/openai"
)

func TestAllChoicesReasoningAndRefusalReachBillingEstimate(t *testing.T) {
	wire := "data: " + `{"choices":[{"index":0,"delta":{"content":"hello","reasoning":"think","refusal":"no"}},{"index":1,"delta":{"content":"world"}}]}` + "\n\ndata: [DONE]\n\n"
	h := nativeHarness(t, openai.Provider{}, openai.ID, wire)
	view := h.do(`{"model":"gpt","stream":true,"n":2,"messages":[{"role":"user","content":"hi"}]}`)
	out := h.outcome()
	if view.status != 200 || out.Terminal != gateway.TerminalCompletedNoUsage || !out.Charge || out.Usage.CompletionTokens != 5 {
		t.Fatalf("17 generated bytes must bill as 5 estimated tokens: view=%+v outcome=%+v", view, out)
	}
}
