// Code generated by api/generate. DO NOT EDIT.
package api

import "net/http"

func (a *domainAdapter) GetWellKnownOpenidConfiguration(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiAuditEvents(w http.ResponseWriter, r *http.Request, params GetApiAuditEventsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiAuditEventsExport(w http.ResponseWriter, r *http.Request, params GetApiAuditEventsExportParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiAuditRequests(w http.ResponseWriter, r *http.Request, params GetApiAuditRequestsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiAuditRequestsRequestAttempts(w http.ResponseWriter, r *http.Request, request string, params GetApiAuditRequestsRequestAttemptsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiAuditSamplesRequest(w http.ResponseWriter, r *http.Request, request string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiAuditUsage(w http.ResponseWriter, r *http.Request, params GetApiAuditUsageParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiAuditUsageExport(w http.ResponseWriter, r *http.Request, params GetApiAuditUsageExportParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiAuditUsageStat(w http.ResponseWriter, r *http.Request, params GetApiAuditUsageStatParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBillingAdjustments(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiBillingBalance(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiBillingEntries(w http.ResponseWriter, r *http.Request, params GetApiBillingEntriesParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiBillingFundingEconomics(w http.ResponseWriter, r *http.Request, params GetApiBillingFundingEconomicsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiBillingHistory(w http.ResponseWriter, r *http.Request, params GetApiBillingHistoryParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) ListBlindBoxAdminPools(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiBlindBoxAdminPools(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiBlindBoxAdminUsersIdGrants(w http.ResponseWriter, r *http.Request, id int64, params DeleteApiBlindBoxAdminUsersIdGrantsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBlindBoxAdminUsersIdGrants(w http.ResponseWriter, r *http.Request, id int64, params PostApiBlindBoxAdminUsersIdGrantsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiBlindBoxAdminUsersIdOverview(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBlindBoxAdminUsersIdRevoke(w http.ResponseWriter, r *http.Request, id int64, params PostApiBlindBoxAdminUsersIdRevokeParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBlindBoxAmount(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiBlindBoxEpayNotify(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBlindBoxEpayNotify(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiBlindBoxEpayReturn(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBlindBoxEpayReturn(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiBlindBoxHistory(w http.ResponseWriter, r *http.Request, params GetApiBlindBoxHistoryParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBlindBoxInventoryGift(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBlindBoxInventoryOpen(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiBlindBoxInventoryOverview(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBlindBoxInventoryPurchase(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiBlindBoxOrdersTradeNo(w http.ResponseWriter, r *http.Request, tradeNo string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBlindBoxOrdersTradeNoCancel(w http.ResponseWriter, r *http.Request, tradeNo string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBlindBoxPay(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBlindBoxPropsIdConvert(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBlindBoxPropsIdGift(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBlindBoxPropsIdPause(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBlindBoxPropsIdUse(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiBlindBoxSelf(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBlindBoxSimulationDraw(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiBlindBoxXunhuNotify(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBlindBoxXunhuNotify(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiBlindBoxXunhuReturn(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiBlindBoxXunhuReturn(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCatalogChannels(w http.ResponseWriter, r *http.Request, params GetApiCatalogChannelsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiCatalogChannels(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiCatalogChannelsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCatalogChannelsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiCatalogChannelsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCatalogChannelsIdCredentials(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiCatalogChannelsIdCredentials(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiCatalogChannelsIdCredentialsCredential(w http.ResponseWriter, r *http.Request, id int64, credential int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiCatalogChannelsIdCredentialsCredential(w http.ResponseWriter, r *http.Request, id int64, credential int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCatalogGroups(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiCatalogGroupsName(w http.ResponseWriter, r *http.Request, name string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiCatalogGroupsName(w http.ResponseWriter, r *http.Request, name string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCatalogModels(w http.ResponseWriter, r *http.Request, params GetApiCatalogModelsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiCatalogModels(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiCatalogModels(w http.ResponseWriter, r *http.Request, params PutApiCatalogModelsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCatalogModelsMissing(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCatalogModelsSearch(w http.ResponseWriter, r *http.Request, params GetApiCatalogModelsSearchParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiCatalogModelsSyncUpstream(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCatalogModelsSyncUpstreamPreview(w http.ResponseWriter, r *http.Request, params GetApiCatalogModelsSyncUpstreamPreviewParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiCatalogModelsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCatalogModelsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiCatalogModelsId(w http.ResponseWriter, r *http.Request, id int64, params PutApiCatalogModelsIdParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCatalogPrefillGroups(w http.ResponseWriter, r *http.Request, params GetApiCatalogPrefillGroupsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiCatalogPrefillGroups(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiCatalogPrefillGroups(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiCatalogPrefillGroupsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiCatalogPrefillGroupsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCatalogPrices(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiCatalogPricesModel(w http.ResponseWriter, r *http.Request, model string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiCatalogPricesModel(w http.ResponseWriter, r *http.Request, model string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCatalogRoutePools(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiCatalogRoutePools(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiCatalogRoutePoolsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCatalogVendors(w http.ResponseWriter, r *http.Request, params GetApiCatalogVendorsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiCatalogVendors(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiCatalogVendors(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCatalogVendorsSearch(w http.ResponseWriter, r *http.Request, params GetApiCatalogVendorsSearchParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiCatalogVendorsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCatalogVendorsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiCatalogVendorsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiChannel(w http.ResponseWriter, r *http.Request, params GetApiChannelParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiChannel(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiChannel(w http.ResponseWriter, r *http.Request) { a.next.ServeHTTP(w, r) }
func (a *domainAdapter) PostApiChannelBatch(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiChannelBatchTag(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiChannelCopyId(w http.ResponseWriter, r *http.Request, id int64, params PostApiChannelCopyIdParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiChannelDisabled(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiChannelFetchModels(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiChannelFetchModelsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiChannelModels(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiChannelModelsEnabled(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiChannelSearch(w http.ResponseWriter, r *http.Request, params GetApiChannelSearchParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiChannelTag(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiChannelTagDisabled(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiChannelTagEnabled(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiChannelTagModels(w http.ResponseWriter, r *http.Request, params GetApiChannelTagModelsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiChannelTest(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiChannelTestId(w http.ResponseWriter, r *http.Request, id int64, params GetApiChannelTestIdParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiChannelId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiChannelId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCommerceAdminOrders(w http.ResponseWriter, r *http.Request, params GetApiCommerceAdminOrdersParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCommerceAdminPackagePaymentReviews(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiCommerceAdminPackagePaymentReviewsIdResolve(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCommerceOrders(w http.ResponseWriter, r *http.Request, params GetApiCommerceOrdersParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiCommerceOrders(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCommerceOrdersTradeNo(w http.ResponseWriter, r *http.Request, tradeNo string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiCommerceOrdersTradeNoCancel(w http.ResponseWriter, r *http.Request, tradeNo string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCommerceOrdersTradeNoDiscount(w http.ResponseWriter, r *http.Request, tradeNo string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCommerceOrdersTradeNoInvoice(w http.ResponseWriter, r *http.Request, tradeNo string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiCommerceOrdersTradeNoInvoice(w http.ResponseWriter, r *http.Request, tradeNo string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCommerceProviders(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiCommerceRedemptionsRedeem(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiCommerceWebhooksProvider(w http.ResponseWriter, r *http.Request, provider string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiCommunityChannelsIdRating(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCommunitySellers(w http.ResponseWriter, r *http.Request, params GetApiCommunitySellersParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiCommunityV1ChannelsIdRating(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCommunityV1MembersSub(w http.ResponseWriter, r *http.Request, sub string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCommunityV1MembersSubChannels(w http.ResponseWriter, r *http.Request, sub string, params GetApiCommunityV1MembersSubChannelsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiCommunityV1Sellers(w http.ResponseWriter, r *http.Request, params GetApiCommunityV1SellersParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiCreemWebhook(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDeployments(w http.ResponseWriter, r *http.Request, params GetApiDeploymentsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiDeployments(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDeploymentsAvailableReplicas(w http.ResponseWriter, r *http.Request, params GetApiDeploymentsAvailableReplicasParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDeploymentsCheckName(w http.ResponseWriter, r *http.Request, params GetApiDeploymentsCheckNameParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDeploymentsHardwareTypes(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDeploymentsLocations(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiDeploymentsPriceEstimation(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDeploymentsSearch(w http.ResponseWriter, r *http.Request, params GetApiDeploymentsSearchParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDeploymentsSettings(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiDeploymentsSettingsTestConnection(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiDeploymentsTestConnection(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiDeploymentsId(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDeploymentsId(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiDeploymentsId(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDeploymentsIdContainers(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDeploymentsIdContainersContainerId(w http.ResponseWriter, r *http.Request, id string, containerId string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiDeploymentsIdExtend(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDeploymentsIdLogs(w http.ResponseWriter, r *http.Request, id string, params GetApiDeploymentsIdLogsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiDeploymentsIdName(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDesktopAccountSummary(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiDesktopAuthApprove(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiDesktopAuthPoll(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiDesktopAuthReject(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDesktopAuthSession(w http.ResponseWriter, r *http.Request, params GetApiDesktopAuthSessionParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiDesktopAuthSession(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDesktopAuthorizedDevices(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiDesktopAuthorizedDevicesId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDesktopConfigTemplate(w http.ResponseWriter, r *http.Request, params GetApiDesktopConfigTemplateParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDesktopConfigTemplates(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDesktopDevices(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiDesktopDevicesId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiDesktopDiagnosticsReport(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDesktopGroupStatus(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDesktopGroups(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDesktopImportConfig(w http.ResponseWriter, r *http.Request, params GetApiDesktopImportConfigParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiDesktopImportDeeplink(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDesktopPricing(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDesktopReleaseLatest(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDesktopReleaseLatestJson(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDesktopServiceStatus(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiDesktopTelemetryEvents(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDesktopTokens(w http.ResponseWriter, r *http.Request, params GetApiDesktopTokensParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiDesktopTokens(w http.ResponseWriter, r *http.Request, params PostApiDesktopTokensParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiDesktopTokens(w http.ResponseWriter, r *http.Request, params PutApiDesktopTokensParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiDesktopTokensEnsure(w http.ResponseWriter, r *http.Request, params PostApiDesktopTokensEnsureParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiDesktopTokensId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDesktopTokensIdConfig(w http.ResponseWriter, r *http.Request, id int64, params GetApiDesktopTokensIdConfigParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiDesktopTokensIdGroup(w http.ResponseWriter, r *http.Request, id int64, params PutApiDesktopTokensIdGroupParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiDesktopTokensIdKey(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDesktopUsageLogs(w http.ResponseWriter, r *http.Request, params GetApiDesktopUsageLogsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiDesktopUsageTrends(w http.ResponseWriter, r *http.Request, params GetApiDesktopUsageTrendsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiGroupBuyCreate(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiGroupBuyJoin(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiGroupBuyList(w http.ResponseWriter, r *http.Request, params GetApiGroupBuyListParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiGroupBuyMine(w http.ResponseWriter, r *http.Request, params GetApiGroupBuyMineParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiGroupBuyId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiGroup(w http.ResponseWriter, r *http.Request) { a.next.ServeHTTP(w, r) }
func (a *domainAdapter) GetApiInvoicesAdminRequests(w http.ResponseWriter, r *http.Request, params GetApiInvoicesAdminRequestsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiInvoicesAdminRequestsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiInvoicesEligibleOrders(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiInvoicesRequests(w http.ResponseWriter, r *http.Request, params GetApiInvoicesRequestsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiInvoicesRequests(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiLog(w http.ResponseWriter, r *http.Request, params GetApiLogParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiLogExport(w http.ResponseWriter, r *http.Request, params GetApiLogExportParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiLogSearch(w http.ResponseWriter, r *http.Request, params GetApiLogSearchParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiLogSelf(w http.ResponseWriter, r *http.Request, params GetApiLogSelfParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiLogSelfExport(w http.ResponseWriter, r *http.Request, params GetApiLogSelfExportParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiLogSelfSearch(w http.ResponseWriter, r *http.Request, params GetApiLogSelfSearchParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiLogSelfStat(w http.ResponseWriter, r *http.Request, params GetApiLogSelfStatParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiLogStat(w http.ResponseWriter, r *http.Request, params GetApiLogStatParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiLogToken(w http.ResponseWriter, r *http.Request, params GetApiLogTokenParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceAdminChannels(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiMarketplaceAdminChannelsId(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PatchApiMarketplaceAdminChannelsId(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceAdminChannelsIdModelsRemoveFailed(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceAdminChannelsIdPause(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceAdminChannelsIdResume(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceAdminChannelsIdReview(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceAdminChannelsIdTest(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceAdminChannelsIdTestFailed(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceAdminChannelsIdVerificationPause(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceAdminChannelsIdVerify(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceAdminOwnerIncome(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceAdminOwnerIncomeReclaimsId(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceAdminOwnerIncomeRelease(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceAdminSecurityAuditEvents(w http.ResponseWriter, r *http.Request, params GetApiMarketplaceAdminSecurityAuditEventsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceAdminSecurityAuditEventsExport(w http.ResponseWriter, r *http.Request, params GetApiMarketplaceAdminSecurityAuditEventsExportParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PatchApiMarketplaceAdminSecurityAuditEventsId(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetAdminMarketShops(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) ReviewMarketShop(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceAutoRoutePool(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiMarketplaceAutoRoutePool(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceBatchTests(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceBatchTestsId(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceChannels(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceChannelsFetchModels(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceChannelsMine(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetChannelOwnerAnalytics(w http.ResponseWriter, r *http.Request, params GetChannelOwnerAnalyticsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) ExportChannelOwnerAnalytics(w http.ResponseWriter, r *http.Request, params ExportChannelOwnerAnalyticsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceChannelsMineBargainRequests(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceChannelsMineBargainRequestsIdResolve(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceChannelsMineLogs(w http.ResponseWriter, r *http.Request, params GetApiMarketplaceChannelsMineLogsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceChannelsMineLogsExport(w http.ResponseWriter, r *http.Request, params GetApiMarketplaceChannelsMineLogsExportParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceChannelsMineObservability(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceChannelsMineUserMultipliers(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceChannelsMineUserMultipliersBatch(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceChannelsMineUserUsage(w http.ResponseWriter, r *http.Request, params GetApiMarketplaceChannelsMineUserUsageParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiMarketplaceChannelsId(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PatchApiMarketplaceChannelsId(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceChannelsIdBatchWelfare(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetChannelMarketDisclosure(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutChannelMarketDisclosure(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceChannelsIdModelsRemoveFailed(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceChannelsIdPause(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceChannelsIdResume(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceChannelsIdTest(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceChannelsIdTestFailed(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceChannelsIdTimeRangeMultipliers(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceChannelsIdTimeRangeMultipliers(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiMarketplaceChannelsIdTimeRangeMultipliersRuleId(w http.ResponseWriter, r *http.Request, id string, ruleId string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceChannelsIdUserBlock(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceChannelsIdUserBlocks(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceChannelsIdUserMultiplier(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceChannelsIdUserUsageUserIdTimeSeries(w http.ResponseWriter, r *http.Request, id string, userId int64, params GetApiMarketplaceChannelsIdUserUsageUserIdTimeSeriesParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceChannelsIdVerificationPause(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceChannelsIdVerify(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceGroupStatus(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceGroups(w http.ResponseWriter, r *http.Request, params GetApiMarketplaceGroupsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceGroupsIdBargainRequests(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceGroupsIdBindToken(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceGroupsIdFeedback(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetChannelMarketInsights(w http.ResponseWriter, r *http.Request, id string, params GetChannelMarketInsightsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceGroupsIdInvite(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetMarketGroupRating(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostMarketGroupRating(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceGroupsSlug(w http.ResponseWriter, r *http.Request, slug string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceGroupsSlugModelStatus(w http.ResponseWriter, r *http.Request, slug string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceInvitesAccept(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceKeyGroupOptions(w http.ResponseWriter, r *http.Request, params GetApiMarketplaceKeyGroupOptionsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceModels(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceMultiplierNotices(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceMultiplierNoticesIdRead(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceMultiplierTrends(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceRoutePools(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceRoutePools(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceRoutePoolsGroupOptions(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiMarketplaceRoutePoolsId(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceRoutePoolsId(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiMarketplaceRoutePoolsId(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceRoutePoolsIdAutoBuildRun(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiMarketplaceRoutePoolsIdBindToken(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceSecurityAuditEvents(w http.ResponseWriter, r *http.Request, params GetApiMarketplaceSecurityAuditEventsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiMarketplaceSecurityAuditEventsExport(w http.ResponseWriter, r *http.Request, params GetApiMarketplaceSecurityAuditEventsExportParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PatchApiMarketplaceSecurityAuditEventsId(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetMyMarketShop(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) UpdateMyMarketShop(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetMarketShops(w http.ResponseWriter, r *http.Request, params GetMarketShopsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetMarketShop(w http.ResponseWriter, r *http.Request, id string, params GetMarketShopParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiModelsWithoutTrailingSlash(w http.ResponseWriter, r *http.Request, params GetApiModelsWithoutTrailingSlashParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiModelsWithoutTrailingSlash(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiModelsWithoutTrailingSlash(w http.ResponseWriter, r *http.Request, params PutApiModelsWithoutTrailingSlashParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiModels(w http.ResponseWriter, r *http.Request, params GetApiModelsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiModels(w http.ResponseWriter, r *http.Request) { a.next.ServeHTTP(w, r) }
func (a *domainAdapter) PutApiModels(w http.ResponseWriter, r *http.Request, params PutApiModelsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiModelsFavorites(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiModelsFavorites(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiModelsFavoritesSlashAlias(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiModelsFavoritesSlashAlias(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiModelsMissing(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiModelsSearch(w http.ResponseWriter, r *http.Request, params GetApiModelsSearchParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiModelsSyncUpstream(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiModelsSyncUpstreamPreview(w http.ResponseWriter, r *http.Request, params GetApiModelsSyncUpstreamPreviewParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiModelsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiModelsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiModelsId(w http.ResponseWriter, r *http.Request, id int64, params PutApiModelsIdParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetNotifications(w http.ResponseWriter, r *http.Request, params GetNotificationsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) StreamNotificationEvents(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) MarkNotificationsReadThrough(w http.ResponseWriter, r *http.Request, params MarkNotificationsReadThroughParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetNotificationSummary(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) SetNotificationReadState(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiNowpaymentsIpn(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiNowpaymentsWebhook(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiOauthEmailBind(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiOauthProviders(w http.ResponseWriter, r *http.Request, params GetApiOauthProvidersParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiOauthProvider(w http.ResponseWriter, r *http.Request, provider string, params GetApiOauthProviderParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiOauthProviderCallback(w http.ResponseWriter, r *http.Request, provider string, params GetApiOauthProviderCallbackParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiOidcAuthorize(w http.ResponseWriter, r *http.Request, params GetApiOidcAuthorizeParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiOidcJwks(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiOidcToken(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiOidcUserinfo(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiOidcUserinfo(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiOption(w http.ResponseWriter, r *http.Request) { a.next.ServeHTTP(w, r) }
func (a *domainAdapter) PutApiOption(w http.ResponseWriter, r *http.Request) { a.next.ServeHTTP(w, r) }
func (a *domainAdapter) GetApiPackagesMySubscription(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiPackagesPublic(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiPackagesPurchase(w http.ResponseWriter, r *http.Request, params PostApiPackagesPurchaseParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiPackagesRenew(w http.ResponseWriter, r *http.Request, params PostApiPackagesRenewParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiPackagesUpgrade(w http.ResponseWriter, r *http.Request, params PostApiPackagesUpgradeParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiPasskey(w http.ResponseWriter, r *http.Request, params GetApiPasskeyParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiPasskeyLoginBegin(w http.ResponseWriter, r *http.Request, params PostApiPasskeyLoginBeginParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiPasskeyLoginFinish(w http.ResponseWriter, r *http.Request, params PostApiPasskeyLoginFinishParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiPasskeyRegisterBegin(w http.ResponseWriter, r *http.Request, params PostApiPasskeyRegisterBeginParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiPasskeyRegisterFinish(w http.ResponseWriter, r *http.Request, params PostApiPasskeyRegisterFinishParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiPerformanceDiskCache(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiPerformanceGc(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiPerformanceLogs(w http.ResponseWriter, r *http.Request, params DeleteApiPerformanceLogsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiPerformanceLogs(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiPerformanceResetStats(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiPerformanceStats(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetCurrentPolicies(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiPrefillGroupWithoutTrailingSlash(w http.ResponseWriter, r *http.Request, params GetApiPrefillGroupWithoutTrailingSlashParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiPrefillGroupWithoutTrailingSlash(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiPrefillGroupWithoutTrailingSlash(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiPrefillGroup(w http.ResponseWriter, r *http.Request, params GetApiPrefillGroupParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiPrefillGroup(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiPrefillGroup(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiPrefillGroupId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiPrefillGroupId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiPublicModels(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiRatioSyncApply(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiRatioSyncChannels(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiRatioSyncFetch(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiRedemption(w http.ResponseWriter, r *http.Request, params GetApiRedemptionParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiRedemption(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiRedemptionId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiResetPassword(w http.ResponseWriter, r *http.Request, params GetApiResetPasswordParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiRoutePools(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiRoutePools(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiRoutePools(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiRoutePoolsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiSecurityAuditEvents(w http.ResponseWriter, r *http.Request, params GetApiSecurityAuditEventsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiSecurityAuditEventsExport(w http.ResponseWriter, r *http.Request, params GetApiSecurityAuditEventsExportParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiSecurityAuditEventsId(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PatchApiSecurityAuditEventsId(w http.ResponseWriter, r *http.Request, id string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiSettings(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiSettingsKey(w http.ResponseWriter, r *http.Request, key string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiSettingsKey(w http.ResponseWriter, r *http.Request, key string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiStatus(w http.ResponseWriter, r *http.Request) { a.next.ServeHTTP(w, r) }
func (a *domainAdapter) PostApiStripeWebhook(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionAdminBind(w http.ResponseWriter, r *http.Request, params PostApiSubscriptionAdminBindParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiSubscriptionAdminPlans(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionAdminPlans(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiSubscriptionAdminPlansId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PatchApiSubscriptionAdminPlansId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiSubscriptionAdminPlansId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiApiSubscriptionAdminRedesignPreview(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiApiSubscriptionAdminRedesignRules(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiApiSubscriptionAdminRedesignRules(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiApiSubscriptionAdminReferralPolicy(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiApiSubscriptionAdminReferralPolicy(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiApiSubscriptionAdminReferralQualifications(w http.ResponseWriter, r *http.Request, params GetApiApiSubscriptionAdminReferralQualificationsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiApiSubscriptionAdminReferralQualificationsIdApprove(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiSubscriptionAdminUserSubscriptionsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiSubscriptionAdminUserSubscriptionsId(w http.ResponseWriter, r *http.Request, id int64, params PutApiSubscriptionAdminUserSubscriptionsIdParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionAdminUserSubscriptionsIdInvalidate(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionAdminUserSubscriptionsIdReset(w http.ResponseWriter, r *http.Request, id int64, params PostApiSubscriptionAdminUserSubscriptionsIdResetParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiSubscriptionAdminUsersIdSubscriptions(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionAdminUsersIdSubscriptions(w http.ResponseWriter, r *http.Request, id int64, params PostApiSubscriptionAdminUsersIdSubscriptionsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiApiSubscriptionAdminWalletConversionReviewId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiApiSubscriptionAdminWalletConversionReviewId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionCreemPay(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiSubscriptionEpayNotify(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionEpayNotify(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionEpayPay(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiSubscriptionEpayReturn(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionEpayReturn(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionFuelPurchase(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionFuelQuote(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionNowpaymentsPay(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiSubscriptionOrdersTradeNo(w http.ResponseWriter, r *http.Request, tradeNo string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionOrdersTradeNoCancel(w http.ResponseWriter, r *http.Request, tradeNo string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiSubscriptionPlans(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiSubscriptionSelf(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiSubscriptionSelfClaudeConversions(w http.ResponseWriter, r *http.Request, params GetApiSubscriptionSelfClaudeConversionsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionSelfClaudeConversions(w http.ResponseWriter, r *http.Request, params PostApiSubscriptionSelfClaudeConversionsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiSubscriptionSelfPreference(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiSubscriptionSelfPreference(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiApiSubscriptionSelfResetCards(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiApiSubscriptionSelfResetCardsConfirm(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiApiSubscriptionSelfResetCardsQuote(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiApiSubscriptionSelfResetCardsRules(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiApiSubscriptionSelfResetCardsIdActivate(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiSubscriptionSelfResetOpportunity(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionSelfResetOpportunityUse(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiApiSubscriptionSelfWalletConversionConfirm(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiApiSubscriptionSelfWalletConversionQuote(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiApiSubscriptionSelfWalletConversionRequestId(w http.ResponseWriter, r *http.Request, requestId string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionStripePay(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionWaffoPancakePay(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionWaffoPay(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiSubscriptionXunhuNotify(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionXunhuNotify(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionXunhuPay(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiSubscriptionXunhuReturn(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiSubscriptionXunhuReturn(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiToken(w http.ResponseWriter, r *http.Request, params GetApiTokenParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiToken(w http.ResponseWriter, r *http.Request, params PostApiTokenParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiToken(w http.ResponseWriter, r *http.Request, params PutApiTokenParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiTokenId(w http.ResponseWriter, r *http.Request, id int64, params DeleteApiTokenIdParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiTokenId(w http.ResponseWriter, r *http.Request, id int64, params GetApiTokenIdParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiTokenIdKey(w http.ResponseWriter, r *http.Request, id int64, params GetApiTokenIdKeyParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiTokenIdKey(w http.ResponseWriter, r *http.Request, id int64, params PostApiTokenIdKeyParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUser(w http.ResponseWriter, r *http.Request, params GetApiUserParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUser(w http.ResponseWriter, r *http.Request, params PostApiUserParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiUser(w http.ResponseWriter, r *http.Request, params PutApiUserParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUser2faBackupCodes(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUser2faDisable(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUser2faEnable(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUser2faSetup(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUser2faStats(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUser2faStatus(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUserAff(w http.ResponseWriter, r *http.Request) { a.next.ServeHTTP(w, r) }
func (a *domainAdapter) GetApiApiUserAffConsumptionRewards(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUserAffOverview(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUserAffRewards(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserAffTransfer(w http.ResponseWriter, r *http.Request, params PostApiUserAffTransferParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserCreemPay(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserEmailVerify(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUserEpayNotify(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserEpayNotify(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUserEpayReturn(w http.ResponseWriter, r *http.Request, params GetApiUserEpayReturnParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserEpayReturn(w http.ResponseWriter, r *http.Request, params PostApiUserEpayReturnParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUserGroups(w http.ResponseWriter, r *http.Request, params GetApiUserGroupsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserLogin(w http.ResponseWriter, r *http.Request, params PostApiUserLoginParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserLogin2fa(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUserLogout(w http.ResponseWriter, r *http.Request, params GetApiUserLogoutParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserLogout(w http.ResponseWriter, r *http.Request, params PostApiUserLogoutParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserNowpaymentsPay(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiUserPasskey(w http.ResponseWriter, r *http.Request, params DeleteApiUserPasskeyParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUserPasskey(w http.ResponseWriter, r *http.Request, params GetApiUserPasskeyParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserPasskeyLoginBegin(w http.ResponseWriter, r *http.Request, params PostApiUserPasskeyLoginBeginParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserPasskeyLoginFinish(w http.ResponseWriter, r *http.Request, params PostApiUserPasskeyLoginFinishParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserPasskeyRegisterBegin(w http.ResponseWriter, r *http.Request, params PostApiUserPasskeyRegisterBeginParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserPasskeyRegisterFinish(w http.ResponseWriter, r *http.Request, params PostApiUserPasskeyRegisterFinishParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserPasskeyVerifyBegin(w http.ResponseWriter, r *http.Request, params PostApiUserPasskeyVerifyBeginParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserPasskeyVerifyFinish(w http.ResponseWriter, r *http.Request, params PostApiUserPasskeyVerifyFinishParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserPay(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetPolicyAcceptances(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) AcceptPolicy(w http.ResponseWriter, r *http.Request) { a.next.ServeHTTP(w, r) }
func (a *domainAdapter) PostApiUserRefresh(w http.ResponseWriter, r *http.Request, params PostApiUserRefreshParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserRegister(w http.ResponseWriter, r *http.Request, params PostApiUserRegisterParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserReset(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUserSelf(w http.ResponseWriter, r *http.Request, params GetApiUserSelfParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiUserSelf(w http.ResponseWriter, r *http.Request, params PutApiUserSelfParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUserSelfGroups(w http.ResponseWriter, r *http.Request, params GetApiUserSelfGroupsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUserSelfSettings(w http.ResponseWriter, r *http.Request, params GetApiUserSelfSettingsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiUserSelfSettings(w http.ResponseWriter, r *http.Request, params PutApiUserSelfSettingsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserStripePay(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUserTopup(w http.ResponseWriter, r *http.Request, params GetApiUserTopupParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserTopup(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUserTopupInfo(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUserTopupSelf(w http.ResponseWriter, r *http.Request, params GetApiUserTopupSelfParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserWaffoPancakePay(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserWaffoPay(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUserXunhuNotify(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserXunhuNotify(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserXunhuPay(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUserXunhuReturn(w http.ResponseWriter, r *http.Request, params GetApiUserXunhuReturnParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiUserXunhuReturn(w http.ResponseWriter, r *http.Request, params PostApiUserXunhuReturnParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiUserId(w http.ResponseWriter, r *http.Request, id int64, params DeleteApiUserIdParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiUserId(w http.ResponseWriter, r *http.Request, id int64, params GetApiUserIdParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiUserId(w http.ResponseWriter, r *http.Request, id int64, params PutApiUserIdParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiUserId2fa(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiVendorsWithoutTrailingSlash(w http.ResponseWriter, r *http.Request, params GetApiVendorsWithoutTrailingSlashParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiVendorsWithoutTrailingSlash(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiVendorsWithoutTrailingSlash(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiVendors(w http.ResponseWriter, r *http.Request, params GetApiVendorsParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiVendors(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiVendors(w http.ResponseWriter, r *http.Request) { a.next.ServeHTTP(w, r) }
func (a *domainAdapter) GetApiVendorsSearch(w http.ResponseWriter, r *http.Request, params GetApiVendorsSearchParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) DeleteApiVendorsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiVendorsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiVendorsId(w http.ResponseWriter, r *http.Request, id int64) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiVerification(w http.ResponseWriter, r *http.Request, params GetApiVerificationParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiWaffoPancakeWebhook(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiWaffoWebhook(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiWallet(w http.ResponseWriter, r *http.Request) { a.next.ServeHTTP(w, r) }
func (a *domainAdapter) PostApiWalletRefunds(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiWalletRefundsEligible(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiWalletRefundsRefundNoSync(w http.ResponseWriter, r *http.Request, refundNo string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiWalletTransfers(w http.ResponseWriter, r *http.Request, params GetApiWalletTransfersParams) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiWalletTransfers(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PutApiWalletTransfersPaymentPassword(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) PostApiWalletTransfersPaymentPasswordEmailCode(w http.ResponseWriter, r *http.Request) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetApiWalletTransfersRecipientsExternalId(w http.ResponseWriter, r *http.Request, externalId string) {
	a.next.ServeHTTP(w, r)
}
func (a *domainAdapter) GetHealthz(w http.ResponseWriter, r *http.Request) { a.next.ServeHTTP(w, r) }
func (a *domainAdapter) GetReadyz(w http.ResponseWriter, r *http.Request)  { a.next.ServeHTTP(w, r) }
