-- Invoice applications record immutable paid-order snapshots and manual outcomes.
CREATE FUNCTION v3_commerce.invoice_minor_scale(currency text) RETURNS integer
LANGUAGE sql IMMUTABLE STRICT AS $$
    SELECT CASE
        WHEN currency IN ('bif','clp','djf','gnf','jpy','kmf','krw','mga','pyg','rwf','ugx','vnd','vuv','xaf','xof','xpf') THEN 1
        WHEN currency IN ('bhd','jod','kwd','omr','tnd') THEN 1000
        ELSE 100
    END
$$;

CREATE TABLE v3_commerce.invoices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    source_type text NOT NULL CHECK (source_type IN ('topup','subscription','batch')),
    trade_no text NOT NULL,
    order_amount_minor bigint NOT NULL CHECK (order_amount_minor > 0),
    order_amount numeric NOT NULL,
    currency text NOT NULL CHECK (currency ~ '^[a-z][a-z0-9]{2,11}$'),
    order_title text NOT NULL,
    order_count integer NOT NULL DEFAULT 1 CHECK (order_count > 0),
    invoice_type text NOT NULL CHECK (invoice_type IN ('personal','enterprise')),
    title text NOT NULL CHECK (length(title) BETWEEN 1 AND 255),
    tax_number text NOT NULL DEFAULT '' CHECK (length(tax_number) <= 64),
    email text NOT NULL CHECK (length(email) BETWEEN 1 AND 255),
    remark text NOT NULL DEFAULT '' CHECK (length(remark) <= 500),
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','issued','rejected')),
    invoice_number text NOT NULL DEFAULT '' CHECK (length(invoice_number) <= 128),
    delivery_method text NOT NULL DEFAULT '',
    document_url text NOT NULL DEFAULT '',
    admin_note text NOT NULL DEFAULT '' CHECK (length(admin_note) <= 1000),
    handled_by bigint NOT NULL DEFAULT 0,
    issued_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (source_type,trade_no),
    CHECK (order_amount * v3_commerce.invoice_minor_scale(currency) = order_amount_minor)
);
CREATE INDEX invoices_user_idx ON v3_commerce.invoices(user_id,id DESC);
CREATE INDEX invoices_status_idx ON v3_commerce.invoices(status,id DESC);

CREATE TABLE v3_commerce.invoice_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id bigint NOT NULL REFERENCES v3_commerce.invoices(id),
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    source_type text NOT NULL CHECK (source_type IN ('topup','subscription')),
    trade_no text NOT NULL REFERENCES v3_commerce.orders(trade_no),
    order_amount_minor bigint NOT NULL CHECK (order_amount_minor > 0),
    order_amount numeric NOT NULL,
    currency text NOT NULL CHECK (currency ~ '^[a-z][a-z0-9]{2,11}$'),
    order_title text NOT NULL,
    paid_at timestamptz NOT NULL,
    UNIQUE (trade_no),
    CHECK (order_amount * v3_commerce.invoice_minor_scale(currency) = order_amount_minor)
);
CREATE INDEX invoice_items_invoice_idx ON v3_commerce.invoice_items(invoice_id);
