-- New policies are opt-in; historical orders and entitlements keep legacy rules.
ALTER TABLE v3_commerce.plans ADD COLUMN policy_version text NOT NULL DEFAULT 'legacy' CHECK(policy_version IN('legacy','standard_v2'));
ALTER TABLE v3_commerce.orders ADD COLUMN policy_version text NOT NULL DEFAULT 'legacy' CHECK(policy_version IN('legacy','standard_v2')),
 ADD COLUMN plan_snapshot jsonb NOT NULL DEFAULT '{}', ADD COLUMN recognized_revenue_credits bigint CHECK(recognized_revenue_credits>=0);
ALTER TABLE v3_commerce.subscriptions ADD COLUMN policy_version text NOT NULL DEFAULT 'legacy' CHECK(policy_version IN('legacy','standard_v2')),
 ADD COLUMN plan_snapshot jsonb NOT NULL DEFAULT '{}', ADD COLUMN converted_at timestamptz, ADD COLUMN benefits_until timestamptz, ADD COLUMN recognized_revenue_credits bigint CHECK(recognized_revenue_credits>=0);
ALTER TABLE v3_commerce.subscription_buckets ADD COLUMN policy_version text NOT NULL DEFAULT 'legacy' CHECK(policy_version IN('legacy','standard_v2'));
ALTER TABLE v3_commerce.redemption_codes ADD COLUMN plan_snapshot jsonb NOT NULL DEFAULT '{}';
ALTER TABLE v3_commerce.plans ADD CONSTRAINT standard_v2_plan_fixed CHECK(policy_version<>'standard_v2' OR
 (credits>0 AND period_credits=0 AND reset_period='never' AND reset_custom_seconds=0 AND NOT group_buy_enabled
 AND group_buy_bonus=0 AND group_buy_bonus2_micro=0 AND group_buy_bonus3_micro=0 AND group_buy_bonus5_micro=0 AND NOT fuel_enabled));
ALTER TABLE v3_commerce.orders ADD CONSTRAINT standard_v2_order_fixed CHECK(policy_version<>'standard_v2' OR
 (credits>0 AND period_credits=0 AND reset_period='never' AND NOT legacy_periodic AND NOT group_buy_enabled AND purchase_type NOT IN('fuel','start_group','join_group')));
ALTER TABLE v3_commerce.subscriptions ADD CONSTRAINT standard_v2_subscription_fixed CHECK(policy_version<>'standard_v2' OR
 (total_credits>0 AND period_credits=0 AND reset_period='never' AND NOT legacy_periodic AND next_reset_at IS NULL));
ALTER TABLE v3_commerce.subscriptions ADD CONSTRAINT converted_subscription_closed CHECK(converted_at IS NULL OR
 (state='canceled' AND next_reset_at IS NULL AND reset_period='never'));
CREATE TABLE v3_commerce.subscription_conversion_rules (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 plan_id bigint NOT NULL REFERENCES v3_commerce.plans(id), basis_key text NOT NULL CHECK(length(basis_key)=64), source_credits bigint NOT NULL CHECK(source_credits>0),
 wallet_credits bigint NOT NULL CHECK(wallet_credits>0), paid_wallet_credits bigint NOT NULL CHECK(paid_wallet_credits>=0 AND paid_wallet_credits<=wallet_credits),
 recognized_revenue_credits bigint CHECK(recognized_revenue_credits>=0),
 refreshed_paid_wallet_credits bigint CHECK(refreshed_paid_wallet_credits>=0 AND refreshed_paid_wallet_credits<=wallet_credits),
 enabled boolean NOT NULL DEFAULT false, reviewed boolean NOT NULL DEFAULT false, revision bigint NOT NULL DEFAULT 1 CHECK(revision>0),
 note text NOT NULL DEFAULT '', updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(plan_id,source_credits,basis_key), CHECK(NOT enabled OR reviewed)
);
CREATE TABLE v3_commerce.subscription_wallet_quotes (
 quote_id text PRIMARY KEY, user_id bigint NOT NULL REFERENCES v3_identity.users(id), subscription_id bigint NOT NULL REFERENCES v3_commerce.subscriptions(id),
 rule_id bigint NOT NULL REFERENCES v3_commerce.subscription_conversion_rules(id), rule_revision bigint NOT NULL,
 source_account_id bigint NOT NULL REFERENCES v3_billing.accounts(id), original_order_id bigint,
 original_total bigint NOT NULL CHECK(original_total>0), source_credits bigint NOT NULL CHECK(source_credits>0),
 target_credits bigint NOT NULL CHECK(target_credits>0), paid_credits bigint NOT NULL CHECK(paid_credits>=0 AND paid_credits<=target_credits), revenue_multiplier_ppm bigint CHECK(revenue_multiplier_ppm>=0),
 fact_hash text NOT NULL, subscription_expires_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE v3_commerce.subscription_wallet_conversions (
 request_id text PRIMARY KEY, quote_id text NOT NULL UNIQUE REFERENCES v3_commerce.subscription_wallet_quotes(quote_id),
 operation_id text NOT NULL UNIQUE REFERENCES v3_commerce.subscription_operations(operation_id),
 user_id bigint NOT NULL REFERENCES v3_identity.users(id), subscription_id bigint NOT NULL REFERENCES v3_commerce.subscriptions(id),
 state text NOT NULL CHECK(state IN('pending','completed','failed')), source_credits bigint NOT NULL CHECK(source_credits>0),
 target_credits bigint NOT NULL CHECK(target_credits>0), paid_credits bigint NOT NULL CHECK(paid_credits>=0 AND paid_credits<=target_credits),
 wallet_account_id bigint REFERENCES v3_billing.accounts(id), failure_reason text NOT NULL DEFAULT '',
 terms_version text NOT NULL, accepted_at timestamptz NOT NULL, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX wallet_conversion_completed_sub_idx ON v3_commerce.subscription_wallet_conversions(subscription_id) WHERE state='completed';
CREATE UNIQUE INDEX wallet_conversion_pending_sub_idx ON v3_commerce.subscription_wallet_conversions(subscription_id) WHERE state='pending';
ALTER TABLE v3_commerce.subscription_reset_opportunity_accounts ADD COLUMN exchanged_total bigint NOT NULL DEFAULT 0 CHECK(exchanged_total>=0);
DO $$ DECLARE c text; BEGIN
 FOR c IN SELECT conname FROM pg_constraint WHERE conrelid='v3_commerce.subscription_reset_opportunity_accounts'::regclass AND contype='c'
 AND pg_get_constraintdef(oid) LIKE '%earned_total = (used_total + available_total)%' LOOP
 EXECUTE format('ALTER TABLE v3_commerce.subscription_reset_opportunity_accounts DROP CONSTRAINT %I',c);
 END LOOP;
END $$;
ALTER TABLE v3_commerce.subscription_reset_opportunity_accounts ADD CONSTRAINT reset_opportunity_conservation CHECK(earned_total=used_total+exchanged_total+available_total);
ALTER TABLE v3_commerce.subscription_reset_opportunity_ledgers DROP CONSTRAINT subscription_reset_opportunity_ledgers_change_type_check;
ALTER TABLE v3_commerce.subscription_reset_opportunity_ledgers ADD CONSTRAINT subscription_reset_opportunity_ledgers_change_type_check CHECK(change_type IN('earn','use','exchange'));
CREATE TABLE v3_commerce.reset_card_rules (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL CHECK(length(name) BETWEEN 1 AND 200),
 reference_plan_id bigint NOT NULL REFERENCES v3_commerce.plans(id), card_plan_id bigint NOT NULL REFERENCES v3_commerce.plans(id),
 credits bigint NOT NULL CHECK(credits>0), cost_per_card bigint NOT NULL CHECK(cost_per_card>=0), baseline_cost bigint NOT NULL CHECK(baseline_cost>=0),
 budget_total bigint NOT NULL CHECK(budget_total>=0), budget_reserved bigint NOT NULL DEFAULT 0 CHECK(budget_reserved>=0 AND budget_reserved<=budget_total),
 incremental_budget_total bigint NOT NULL CHECK(incremental_budget_total>=0), incremental_reserved bigint NOT NULL DEFAULT 0 CHECK(incremental_reserved>=0 AND incremental_reserved<=incremental_budget_total),
 enabled boolean NOT NULL DEFAULT false, reviewed boolean NOT NULL DEFAULT false, revision bigint NOT NULL DEFAULT 1 CHECK(revision>0),
 note text NOT NULL DEFAULT '', updated_at timestamptz NOT NULL DEFAULT now(), CHECK(NOT enabled OR reviewed)
);
CREATE TABLE v3_commerce.reset_card_quotes (
 quote_id text PRIMARY KEY, user_id bigint NOT NULL REFERENCES v3_identity.users(id), rule_id bigint NOT NULL REFERENCES v3_commerce.reset_card_rules(id),
 rule_revision bigint NOT NULL, quantity integer NOT NULL CHECK(quantity BETWEEN 1 AND 100), available_snapshot bigint NOT NULL CHECK(available_snapshot>=0),
 plan_snapshot jsonb NOT NULL, total_cost bigint NOT NULL CHECK(total_cost>=0), incremental_cost bigint NOT NULL CHECK(incremental_cost>=0),
 expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE v3_commerce.reset_card_exchanges (
 request_id text PRIMARY KEY, quote_id text NOT NULL UNIQUE REFERENCES v3_commerce.reset_card_quotes(quote_id),
 user_id bigint NOT NULL REFERENCES v3_identity.users(id), rule_id bigint NOT NULL REFERENCES v3_commerce.reset_card_rules(id),
 quantity integer NOT NULL CHECK(quantity BETWEEN 1 AND 100), total_cost bigint NOT NULL CHECK(total_cost>=0), incremental_cost bigint NOT NULL CHECK(incremental_cost>=0),
 terms_version text NOT NULL, accepted_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE v3_commerce.bound_subscription_cards (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES v3_identity.users(id),
 exchange_request_id text NOT NULL REFERENCES v3_commerce.reset_card_exchanges(request_id), ordinal integer NOT NULL CHECK(ordinal>=0),
 plan_snapshot jsonb NOT NULL, state text NOT NULL DEFAULT 'ready' CHECK(state IN('ready','activated')),
 activation_request_id text UNIQUE, subscription_id bigint UNIQUE REFERENCES v3_commerce.subscriptions(id),
 activated_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(exchange_request_id,ordinal),
 CHECK((state='ready' AND subscription_id IS NULL AND activated_at IS NULL) OR (state='activated' AND subscription_id IS NOT NULL AND activated_at IS NOT NULL))
);
CREATE INDEX bound_cards_user_idx ON v3_commerce.bound_subscription_cards(user_id,id DESC);
