-- Stop new legacy invitation resets at migration; preserve older order promises.
-- Consumption rewards stay disabled until reviewed economics and budget are configured.
ALTER TABLE v3_commerce.orders ADD COLUMN referral_terms jsonb NOT NULL DEFAULT '{}'::jsonb;
CREATE TABLE v3_commerce.referral_consumption_policy (
 id boolean PRIMARY KEY DEFAULT true CHECK(id), enabled boolean NOT NULL DEFAULT false,
 revision bigint NOT NULL DEFAULT 1 CHECK(revision>0), effective_at timestamptz, ancillary_cost_ppm bigint CHECK(ancillary_cost_ppm BETWEEN 0 AND 1000000), reward_ppm bigint NOT NULL DEFAULT 10000 CHECK(reward_ppm BETWEEN 0 AND 10000),
 profit_share_ppm bigint NOT NULL DEFAULT 200000 CHECK(profit_share_ppm BETWEEN 0 AND 200000),
 window_days integer NOT NULL DEFAULT 30 CHECK(window_days BETWEEN 1 AND 30), delay_days integer NOT NULL DEFAULT 7 CHECK(delay_days BETWEEN 7 AND 90),
 max_reward_credits bigint NOT NULL DEFAULT 0 CHECK(max_reward_credits>=0), total_budget_credits bigint NOT NULL DEFAULT 0 CHECK(total_budget_credits>=0),
 reserved_credits bigint NOT NULL DEFAULT 0 CHECK(reserved_credits>=0), spent_credits bigint NOT NULL DEFAULT 0 CHECK(spent_credits>=0),
 updated_at timestamptz NOT NULL DEFAULT now(), CHECK(reserved_credits::numeric+spent_credits<=total_budget_credits),
 CHECK(NOT enabled OR (max_reward_credits>0 AND total_budget_credits>0 AND effective_at IS NOT NULL AND ancillary_cost_ppm IS NOT NULL))
);
INSERT INTO v3_commerce.referral_consumption_policy(id,effective_at) VALUES(true,now());
CREATE TABLE v3_commerce.referral_consumption_qualifications (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id bigint NOT NULL UNIQUE REFERENCES v3_commerce.orders(id),
 inviter_id bigint NOT NULL REFERENCES v3_identity.users(id), invitee_id bigint NOT NULL REFERENCES v3_identity.users(id),
 state text NOT NULL CHECK(state IN('reserved','active','released','needs_review','completed','refunded')),
 reason text NOT NULL DEFAULT '', terms jsonb NOT NULL,
 reward_ppm bigint NOT NULL CHECK(reward_ppm BETWEEN 0 AND 10000), profit_share_ppm bigint NOT NULL CHECK(profit_share_ppm BETWEEN 0 AND 200000), ancillary_cost_ppm bigint NOT NULL CHECK(ancillary_cost_ppm BETWEEN 0 AND 1000000),
 window_days integer NOT NULL CHECK(window_days BETWEEN 1 AND 30), delay_days integer NOT NULL CHECK(delay_days BETWEEN 7 AND 90),
 max_reward_credits bigint NOT NULL CHECK(max_reward_credits>0), reserved_credits bigint NOT NULL CHECK(reserved_credits>=0),
 paid_credits bigint NOT NULL DEFAULT 0 CHECK(paid_credits>=0), refunded_reward_credits bigint NOT NULL DEFAULT 0 CHECK(refunded_reward_credits>=0),
 net_revenue_credits bigint NOT NULL DEFAULT 0 CHECK(net_revenue_credits>=0), net_cost_credits bigint NOT NULL DEFAULT 0 CHECK(net_cost_credits>=0),
 paid_at timestamptz, window_until timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CHECK(inviter_id<>invitee_id), CHECK(paid_credits::numeric-refunded_reward_credits+reserved_credits<=max_reward_credits), CHECK(refunded_reward_credits<=paid_credits)
);
CREATE UNIQUE INDEX referral_consumption_first_invitee_idx ON v3_commerce.referral_consumption_qualifications(invitee_id)
 WHERE state IN('reserved','active','completed');
CREATE INDEX referral_consumption_pending_idx ON v3_commerce.referral_consumption_qualifications(updated_at,id) WHERE state IN('active','needs_review','completed');
CREATE TABLE v3_commerce.referral_consumption_payouts (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, qualification_id bigint NOT NULL REFERENCES v3_commerce.referral_consumption_qualifications(id),
 operation_id text NOT NULL UNIQUE CHECK(operation_id<>''), amount_credits bigint NOT NULL CHECK(amount_credits>0),
 offset_credits bigint NOT NULL DEFAULT 0 CHECK(offset_credits>=0 AND offset_credits<=amount_credits),
 ledger_entry_id bigint REFERENCES v3_billing.ledger_entries(id), created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE v3_commerce.referral_consumption_offsets (
 user_id bigint PRIMARY KEY REFERENCES v3_identity.users(id), debt_credits bigint NOT NULL DEFAULT 0 CHECK(debt_credits>=0), updated_at timestamptz NOT NULL DEFAULT now()
);
