-- Existing identity records remain consumable after offline import.
-- Imported account bookkeeping is retained for reconciliation. These fields
-- are not spendable balances; current funds live in v3_billing accounts.
ALTER TABLE v3_identity.users ADD COLUMN stripe_customer text NOT NULL DEFAULT '';
ALTER TABLE v3_identity.users ADD COLUMN affiliate_count bigint NOT NULL DEFAULT 0;
ALTER TABLE v3_identity.users ADD COLUMN affiliate_history bigint NOT NULL DEFAULT 0;
ALTER TABLE v3_identity.users ADD COLUMN used_credits bigint NOT NULL DEFAULT 0;
ALTER TABLE v3_identity.users ADD COLUMN request_count bigint NOT NULL DEFAULT 0;
ALTER TABLE v3_identity.passkeys ADD COLUMN legacy_id bigint UNIQUE;
ALTER TABLE v3_identity.passkeys ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE v3_identity.user_identities ADD COLUMN legacy_binding_id bigint UNIQUE;
CREATE TABLE v3_identity.oauth_providers (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name text NOT NULL,
 slug text NOT NULL UNIQUE,
 icon text NOT NULL DEFAULT '',
 enabled boolean NOT NULL DEFAULT false,
 client_id text NOT NULL DEFAULT '',
 secret_ciphertext bytea NOT NULL,
 authorization_endpoint text NOT NULL DEFAULT '',
 token_endpoint text NOT NULL DEFAULT '',
 user_info_endpoint text NOT NULL DEFAULT '',
 scopes text NOT NULL DEFAULT 'openid profile email',
 user_id_field text NOT NULL DEFAULT 'sub',
 username_field text NOT NULL DEFAULT 'preferred_username',
 display_name_field text NOT NULL DEFAULT 'name',
 email_field text NOT NULL DEFAULT 'email',
 well_known text NOT NULL DEFAULT '',
 auth_style integer NOT NULL DEFAULT 0 CHECK(auth_style BETWEEN 0 AND 2),
 access_policy text NOT NULL DEFAULT '',
 access_denied_message text NOT NULL DEFAULT '',
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);
