-- Retained commercial facts are typed, so offline import and pending payment
-- recovery can preserve source prices, ownership and benefit eligibility.
ALTER TABLE v3_commerce.plans
    ADD COLUMN subtitle text NOT NULL DEFAULT '',
    ADD COLUMN sort_order integer NOT NULL DEFAULT 0,
    ADD COLUMN stripe_price_id text NOT NULL DEFAULT '',
    ADD COLUMN creem_product_id text NOT NULL DEFAULT '',
    ADD COLUMN price_amount numeric NOT NULL DEFAULT 0,
    ADD COLUMN group_buy_bonus2 numeric NOT NULL DEFAULT 0,
    ADD COLUMN group_buy_bonus3 numeric NOT NULL DEFAULT 0,
    ADD COLUMN group_buy_bonus5 numeric NOT NULL DEFAULT 0,
    ADD COLUMN fuel_unit_price numeric NOT NULL DEFAULT 0,
    ADD COLUMN upgrade_group text NOT NULL DEFAULT '',
    ADD COLUMN blind_box_benefit_count bigint NOT NULL DEFAULT 0 CHECK(blind_box_benefit_count>=0),
    -- Historical plan metadata does not enable a retired lottery runtime.
    ADD COLUMN lucky_draw_enabled boolean NOT NULL DEFAULT false;

ALTER TABLE v3_commerce.subscriptions
    ADD COLUMN original_status text NOT NULL DEFAULT '',
    ADD COLUMN upgrade_group text NOT NULL DEFAULT '',
    ADD COLUMN prev_user_group text NOT NULL DEFAULT '',
    ADD COLUMN lucky_benefit_cycle text NOT NULL DEFAULT '',
    ADD COLUMN membership_tier text NOT NULL DEFAULT '',
    ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE v3_commerce.orders
    ADD COLUMN legacy_id bigint,
    ADD COLUMN payment_method text NOT NULL DEFAULT '',
    ADD COLUMN wallet_type text NOT NULL DEFAULT '',
    ADD COLUMN provider_payload text NOT NULL DEFAULT '',
    ADD COLUMN money numeric NOT NULL DEFAULT 0,
    ADD COLUMN original_money numeric NOT NULL DEFAULT 0,
    ADD COLUMN discount_applied boolean NOT NULL DEFAULT false,
    ADD COLUMN discount_multiplier numeric NOT NULL DEFAULT 0,
    ADD COLUMN discount_starts_at timestamptz,
    ADD COLUMN discount_ends_at timestamptz,
    ADD COLUMN refund_state text NOT NULL DEFAULT '',
    ADD COLUMN refund_no text NOT NULL DEFAULT '',
    ADD COLUMN refund_provider_id text NOT NULL DEFAULT '',
    ADD COLUMN refund_minor bigint NOT NULL DEFAULT 0 CHECK(refund_minor>=0),
    ADD COLUMN refund_amount numeric NOT NULL DEFAULT 0,
    ADD COLUMN refund_credits bigint NOT NULL DEFAULT 0 CHECK(refund_credits>=0),
    ADD COLUMN refund_updated_at timestamptz,
    ADD COLUMN group_buy_id bigint NOT NULL DEFAULT 0 CHECK(group_buy_id>=0),
    ADD COLUMN fuel_credits bigint NOT NULL DEFAULT 0 CHECK(fuel_credits>=0),
    ADD COLUMN fuel_unit_price numeric NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX orders_legacy_origin_idx ON v3_commerce.orders(kind,legacy_id) WHERE legacy_id IS NOT NULL;

ALTER TABLE v3_commerce.redemption_codes
    ADD COLUMN creator_id bigint NOT NULL DEFAULT 0,
    ADD COLUMN redeem_type text NOT NULL DEFAULT 'credits' CHECK(redeem_type IN('credits','subscription','blind_box')),
    ADD COLUMN plan_id bigint NOT NULL DEFAULT 0,
    ADD COLUMN plan_title text NOT NULL DEFAULT '',
    ADD COLUMN blind_box_quantity integer NOT NULL DEFAULT 0,
    ADD COLUMN wallet_type text NOT NULL DEFAULT '',
    ADD COLUMN deleted_at timestamptz,
    DROP CONSTRAINT redemption_codes_credits_check;
ALTER TABLE v3_commerce.redemption_codes ADD CONSTRAINT redemption_codes_benefit_check CHECK(
    credits>=0 AND ((redeem_type='credits' AND credits>0) OR
    (redeem_type='subscription' AND plan_id>0) OR
    (redeem_type='blind_box' AND blind_box_quantity>0)));

-- Terminal source consumption records remain queryable financial history.
-- The importer rejects in-flight records before writing this table.
CREATE TABLE v3_commerce.subscription_preconsumes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id text NOT NULL,
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    subscription_id bigint NOT NULL REFERENCES v3_commerce.subscriptions(id),
    model_name text NOT NULL,
    amount bigint NOT NULL CHECK(amount>=0),
    status text NOT NULL CHECK(status IN('consumed','refunded','settled','completed')),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);
CREATE INDEX subscription_preconsumes_request_idx ON v3_commerce.subscription_preconsumes(request_id);
