-- Existing entitlement facts become live state only after explicit restoration.
CREATE TABLE v3_commerce.subscription_lucky_numbers (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, subscription_id bigint NOT NULL UNIQUE REFERENCES v3_commerce.subscriptions(id),
 user_id bigint NOT NULL REFERENCES v3_identity.users(id), card_code text NOT NULL UNIQUE, lucky_suffix text NOT NULL CHECK(lucky_suffix ~ '^[0-9]{4}$'),
 assigned_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE v3_commerce.blind_box_daily_lucky_numbers (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, open_record_id bigint NOT NULL UNIQUE REFERENCES v3_marketplace.blind_box_open_records(id),
 user_id bigint NOT NULL REFERENCES v3_identity.users(id), draw_date text NOT NULL, lucky_suffix text NOT NULL CHECK(lucky_suffix ~ '^[0-9]{4}$'),
 expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX blind_box_lucky_date_idx ON v3_commerce.blind_box_daily_lucky_numbers(draw_date,expires_at);
CREATE TABLE v3_commerce.subscription_lucky_draws (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, draw_date text NOT NULL UNIQUE, winning_number text NOT NULL CHECK(winning_number ~ '^[0-9]{4}$'),
 jackpot_before numeric NOT NULL CHECK(jackpot_before>=0), jackpot_after numeric NOT NULL CHECK(jackpot_after>=0), full_match_count bigint NOT NULL DEFAULT 0 CHECK(full_match_count>=0),
 status text NOT NULL CHECK(status IN('pending','settling','failed','completed')), error_message text NOT NULL DEFAULT '', timezone text NOT NULL,
 draw_hour bigint NOT NULL CHECK(draw_hour BETWEEN 0 AND 23), draw_minute bigint NOT NULL CHECK(draw_minute BETWEEN 0 AND 59),
 base_reward_1_usd numeric NOT NULL, base_reward_2_usd numeric NOT NULL, base_reward_3_usd numeric NOT NULL, base_reward_4_usd numeric NOT NULL,
 multiplier_lite numeric NOT NULL, multiplier_standard numeric NOT NULL, multiplier_pro numeric NOT NULL, multiplier_ultra numeric NOT NULL,
 jackpot_initial_usd numeric NOT NULL, jackpot_increment_usd numeric NOT NULL, jackpot_cap_usd numeric NOT NULL, cost_per_usd numeric NOT NULL, monthly_budget_usd numeric NOT NULL,
 drawn_at timestamptz, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE v3_commerce.subscription_lucky_rewards (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, draw_id bigint NOT NULL REFERENCES v3_commerce.subscription_lucky_draws(id),
 subscription_id bigint REFERENCES v3_commerce.subscriptions(id), open_record_id bigint REFERENCES v3_marketplace.blind_box_open_records(id), participation_type text NOT NULL CHECK(participation_type IN('subscription','blind_box')),
 user_id bigint NOT NULL REFERENCES v3_identity.users(id), lucky_number text NOT NULL CHECK(lucky_number ~ '^[0-9]{4}$'), membership_tier text NOT NULL,
 matched_digits bigint NOT NULL CHECK(matched_digits BETWEEN 0 AND 4), base_reward_usd numeric NOT NULL, tier_multiplier numeric NOT NULL, jackpot_reward_usd numeric NOT NULL,
 final_reward_credits bigint NOT NULL CHECK(final_reward_credits>=0), credit_status text NOT NULL CHECK(credit_status IN('pending','failed','credited')), credit_error text NOT NULL DEFAULT '',
 credited_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(draw_id,subscription_id), UNIQUE(draw_id,open_record_id),
 CHECK((participation_type='subscription' AND subscription_id IS NOT NULL AND open_record_id IS NULL) OR (participation_type='blind_box' AND subscription_id IS NULL AND open_record_id IS NOT NULL))
);
CREATE INDEX lucky_rewards_user_idx ON v3_commerce.subscription_lucky_rewards(user_id,id DESC);
CREATE INDEX lucky_rewards_pending_idx ON v3_commerce.subscription_lucky_rewards(draw_id,id) WHERE credit_status<>'credited';
CREATE TABLE v3_commerce.subscription_lucky_reward_notifications (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, reward_id bigint NOT NULL UNIQUE REFERENCES v3_commerce.subscription_lucky_rewards(id),
 user_id bigint NOT NULL REFERENCES v3_identity.users(id), read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX lucky_notifications_user_idx ON v3_commerce.subscription_lucky_reward_notifications(user_id,id DESC);
CREATE TABLE v3_commerce.subscription_reset_opportunity_accounts (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL UNIQUE REFERENCES v3_identity.users(id),
 earned_total bigint NOT NULL DEFAULT 0 CHECK(earned_total>=0), used_total bigint NOT NULL DEFAULT 0 CHECK(used_total>=0), available_total bigint NOT NULL DEFAULT 0 CHECK(available_total>=0),
 last_used_month text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK(earned_total=used_total+available_total)
);
CREATE TABLE v3_commerce.subscription_reset_opportunity_ledgers (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES v3_identity.users(id), related_user_id bigint REFERENCES v3_identity.users(id), related_subscription_id bigint REFERENCES v3_commerce.subscriptions(id),
 change_type text NOT NULL CHECK(change_type IN('earn','use')), delta bigint NOT NULL CHECK(delta IN(-1,1)), balance_after bigint NOT NULL CHECK(balance_after>=0),
 used_month text NOT NULL DEFAULT '', source_type text NOT NULL DEFAULT '', source_ref text NOT NULL DEFAULT '', event_key text NOT NULL UNIQUE, note text NOT NULL DEFAULT '',
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX reset_opportunities_user_idx ON v3_commerce.subscription_reset_opportunity_ledgers(user_id,id DESC);
CREATE TABLE v3_commerce.referral_purchase_rewards (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, inviter_id bigint NOT NULL REFERENCES v3_identity.users(id), invitee_id bigint NOT NULL UNIQUE REFERENCES v3_identity.users(id),
 purchase_type text NOT NULL, purchase_label text NOT NULL DEFAULT '', bonus_credits bigint NOT NULL CHECK(bonus_credits>=0), order_source_type text NOT NULL, order_source_id text NOT NULL,
 rewarded_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE v3_commerce.subscription_blind_box_benefit_cycles (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, subscription_id bigint NOT NULL REFERENCES v3_commerce.subscriptions(id), benefit_cycle text NOT NULL,
 user_id bigint NOT NULL REFERENCES v3_identity.users(id), membership_tier text NOT NULL, expected_count bigint NOT NULL CHECK(expected_count>=0), granted_count bigint NOT NULL CHECK(granted_count>=0),
 source text NOT NULL, idempotency_key text NOT NULL UNIQUE, starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, status text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(subscription_id,benefit_cycle)
);
CREATE TABLE v3_commerce.subscription_value_conversions (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES v3_identity.users(id), subscription_id bigint NOT NULL REFERENCES v3_commerce.subscriptions(id), request_id text NOT NULL UNIQUE,
 status text NOT NULL, source_credits bigint NOT NULL CHECK(source_credits>=0), target_credits bigint NOT NULL CHECK(target_credits>=0), plan_price_amount numeric NOT NULL, unused_ratio numeric NOT NULL,
 conversion_percent bigint NOT NULL, ratio_numerator bigint NOT NULL, ratio_denominator bigint NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
