-- User supplied channels remain in the shared catalog. Marketplace metadata
-- and permissions have a separate owner so private groups cannot be mistaken
-- for unrestricted catalog groups.
CREATE SCHEMA v3_channelmarket;
ALTER TABLE v3_catalog.groups ALTER COLUMN multiplier TYPE numeric(20,6);

CREATE TABLE v3_channelmarket.groups (
    id text PRIMARY KEY,
    public_channel_id text NOT NULL UNIQUE,
    channel_id bigint NOT NULL UNIQUE REFERENCES v3_catalog.channels(id),
    owner_user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    public_slug text NOT NULL UNIQUE,
    internal_group_name text NOT NULL UNIQUE REFERENCES v3_catalog.groups(name),
    display_name text NOT NULL,
    source_label text NOT NULL DEFAULT '',
    owner_display_name text NOT NULL DEFAULT '',
    source_type text NOT NULL DEFAULT 'marketplace_user',
    credit_pool_policy text NOT NULL DEFAULT 'marketplace_subscription_and_universal',
    routing_version bigint NOT NULL DEFAULT 1,
    published_at timestamptz,
    verification_due_at timestamptz,
    multiplier_ppm bigint NOT NULL DEFAULT 1000000 CHECK(multiplier_ppm>0),
    visibility text NOT NULL DEFAULT 'private' CHECK(visibility IN ('public','unlisted','private')),
    lifecycle_status text NOT NULL DEFAULT 'draft' CHECK(lifecycle_status IN ('draft','verifying','active','paused','rejected','deleted')),
    verification_status text NOT NULL DEFAULT 'pending' CHECK(verification_status IN ('pending','queued','running','passed','failed','paused')),
    review_reason text NOT NULL DEFAULT '',
    model_prices jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
CREATE INDEX channelmarket_groups_owner_idx ON v3_channelmarket.groups(owner_user_id,id);
CREATE TABLE v3_channelmarket.group_invites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id text NOT NULL REFERENCES v3_channelmarket.groups(id),
    created_by bigint NOT NULL REFERENCES v3_identity.users(id),
    token_hash bytea NOT NULL UNIQUE CHECK(octet_length(token_hash)=32),
    expires_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE v3_channelmarket.group_access (
    legacy_id bigint UNIQUE,
    group_id text NOT NULL REFERENCES v3_channelmarket.groups(id),
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    invite_id bigint REFERENCES v3_channelmarket.group_invites(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(group_id,user_id)
);
CREATE TABLE v3_channelmarket.channel_user_blocks (
    legacy_id bigint UNIQUE,
    channel_id bigint NOT NULL REFERENCES v3_catalog.channels(id),
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(channel_id,user_id)
);
CREATE TABLE v3_channelmarket.user_multipliers (
    legacy_id bigint UNIQUE,
    channel_id bigint NOT NULL REFERENCES v3_catalog.channels(id),
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    multiplier_ppm bigint NOT NULL CHECK(multiplier_ppm>0),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(channel_id,user_id)
);
CREATE TABLE v3_channelmarket.time_range_multipliers (
    id text PRIMARY KEY,
    channel_id bigint NOT NULL REFERENCES v3_catalog.channels(id),
    starts_at timestamptz NOT NULL,
    ends_at timestamptz NOT NULL,
    multiplier_ppm bigint NOT NULL CHECK(multiplier_ppm>0),
    label text NOT NULL DEFAULT '',
    CHECK(ends_at>starts_at)
);
CREATE TABLE v3_channelmarket.multiplier_notices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id bigint NOT NULL REFERENCES v3_catalog.channels(id),
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    previous_ppm bigint NOT NULL,
    multiplier_ppm bigint NOT NULL,
    cleared boolean NOT NULL DEFAULT false,
    source text NOT NULL DEFAULT 'manual',
    created_at timestamptz NOT NULL DEFAULT now(),
    read_at timestamptz
);
CREATE TABLE v3_channelmarket.bargain_requests (
    id text PRIMARY KEY,
    group_id text NOT NULL REFERENCES v3_channelmarket.groups(id),
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    proposed_ppm bigint NOT NULL CHECK(proposed_ppm>0),
    status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','accepted','rejected')),
    reason text NOT NULL DEFAULT '',
    resolution_note text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    resolved_at timestamptz
);
CREATE UNIQUE INDEX channelmarket_pending_bargain_idx ON v3_channelmarket.bargain_requests(group_id,user_id) WHERE status='pending';
CREATE TABLE v3_channelmarket.route_pools (
    id text PRIMARY KEY,
    owner_user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    name text NOT NULL,
    internal_group_name text NOT NULL UNIQUE REFERENCES v3_catalog.groups(name),
    strategy text NOT NULL DEFAULT 'weighted' CHECK(strategy IN ('weighted','priority','score','cost','round_robin','fill_first')),
    max_attempts integer NOT NULL DEFAULT 3 CHECK(max_attempts BETWEEN 1 AND 32),
    failure_cooldown_seconds integer NOT NULL DEFAULT 30 CHECK(failure_cooldown_seconds BETWEEN 0 AND 3600),
    max_multiplier_ppm bigint NOT NULL DEFAULT 0 CHECK(max_multiplier_ppm>=0),
    config jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(owner_user_id,name)
);
CREATE TABLE v3_channelmarket.route_pool_members (
    legacy_id bigint,
    legacy_source text NOT NULL DEFAULT '',
    pool_id text NOT NULL REFERENCES v3_channelmarket.route_pools(id) ON DELETE CASCADE,
    group_id text NOT NULL, -- market group id or official:<catalog group>
    catalog_group_name text REFERENCES v3_catalog.groups(name),
    priority integer NOT NULL DEFAULT 0,
    PRIMARY KEY(pool_id,group_id),
    UNIQUE(legacy_source,legacy_id)
);
CREATE TABLE v3_channelmarket.settlements (
    id text PRIMARY KEY,
    request_id text NOT NULL UNIQUE,
    group_id text REFERENCES v3_channelmarket.groups(id),
    channel_id bigint NOT NULL REFERENCES v3_catalog.channels(id),
    owner_user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    consumer_user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    billing_source text NOT NULL DEFAULT 'wallet',
    consumer_micro bigint NOT NULL CHECK(consumer_micro>=0),
    gross_micro bigint NOT NULL CHECK(gross_micro>=0),
    commission_micro bigint NOT NULL CHECK(commission_micro>=0),
    fee_micro bigint NOT NULL CHECK(fee_micro>=0),
    net_micro bigint NOT NULL CHECK(net_micro>=0),
    reclaimed_micro bigint NOT NULL DEFAULT 0 CHECK(reclaimed_micro>=0 AND reclaimed_micro<=net_micro),
    multiplier_ppm bigint NOT NULL DEFAULT 1000000,
    subscription_multiplier_ppm bigint NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','released','reclaimed','forfeited')),
    available_at timestamptz NOT NULL,
    released_at timestamptz,
    reclaimed_at timestamptz,
    forfeited_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK(gross_micro=commission_micro+fee_micro+net_micro)
);
CREATE INDEX channelmarket_income_release_idx ON v3_channelmarket.settlements(available_at,id) WHERE status='pending';
CREATE INDEX channelmarket_income_owner_idx ON v3_channelmarket.settlements(owner_user_id,created_at);
CREATE TABLE v3_channelmarket.verification_runs (
    id text PRIMARY KEY,
    channel_id bigint NOT NULL REFERENCES v3_catalog.channels(id),
    status text NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','running','passed','failed','paused')),
    trigger text NOT NULL DEFAULT 'owner',
    target_model text NOT NULL DEFAULT '',
    results jsonb NOT NULL DEFAULT '[]',
    summary text NOT NULL DEFAULT '',
    stage text NOT NULL DEFAULT '',
    detector_name text NOT NULL DEFAULT '',
    detector_version text NOT NULL DEFAULT '',
    ruleset_version text NOT NULL DEFAULT '',
    evidence_hash text NOT NULL DEFAULT '',
    expires_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    started_at timestamptz,
    completed_at timestamptz
);
CREATE UNIQUE INDEX channelmarket_verification_active_idx ON v3_channelmarket.verification_runs(channel_id) WHERE status IN ('queued','running');
CREATE TABLE v3_channelmarket.income_reclaims (
    id text PRIMARY KEY,
    actor_user_id bigint REFERENCES v3_identity.users(id),
    fingerprint bytea NOT NULL CHECK(octet_length(fingerprint)=32),
    response jsonb NOT NULL,
    filter jsonb NOT NULL DEFAULT '{}',
    status text NOT NULL DEFAULT 'completed' CHECK(status IN ('pending','running','completed','failed')),
    count bigint NOT NULL DEFAULT 0,
    amount_micro bigint NOT NULL DEFAULT 0,
    owner_amounts jsonb NOT NULL DEFAULT '{}',
    batch_number bigint NOT NULL DEFAULT 0,
    error_message text NOT NULL DEFAULT '',
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE v3_channelmarket.security_audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id bigint REFERENCES v3_catalog.channels(id),
    actor_user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    kind text NOT NULL,
    status text NOT NULL DEFAULT 'open' CHECK(status IN ('open','resolved','ignored')),
    details jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE v3_channelmarket.channel_feedback (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id bigint NOT NULL REFERENCES v3_catalog.channels(id),
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    status text NOT NULL DEFAULT 'open',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE v3_channelmarket.batch_tests (
    id text PRIMARY KEY,
    owner_user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    model text NOT NULL,
    status text NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','running','completed','failed')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE v3_channelmarket.batch_test_items (
    batch_id text NOT NULL REFERENCES v3_channelmarket.batch_tests(id),
    group_id text NOT NULL,
    group_name text NOT NULL,
    internal_group_name text NOT NULL REFERENCES v3_catalog.groups(name),
    status text NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','running','passed','failed')),
    latency_ms bigint NOT NULL DEFAULT 0,
    amount_micro bigint NOT NULL DEFAULT 0 CHECK(amount_micro>=0),
    request_id text NOT NULL DEFAULT '',
    billing_source text NOT NULL DEFAULT '',
    log_created boolean NOT NULL DEFAULT false,
    error_message text NOT NULL DEFAULT '',
    started_at timestamptz,
    dispatched_at timestamptz,
    ended_at timestamptz,
    PRIMARY KEY(batch_id,group_id)
);
CREATE TABLE v3_channelmarket.pelican_artifacts (
    group_id text NOT NULL REFERENCES v3_channelmarket.groups(id),
    channel_id bigint NOT NULL REFERENCES v3_catalog.channels(id),
    model text NOT NULL,
    svg text NOT NULL,
    trigger text NOT NULL,
    trigger_user_id bigint REFERENCES v3_identity.users(id),
    request_id text NOT NULL DEFAULT '',
    duration_ms bigint NOT NULL DEFAULT 0,
    generated_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY(group_id,model)
);
CREATE TABLE v3_channelmarket.gpt56_mapping_runs (
    id text PRIMARY KEY,
    channel_id bigint NOT NULL REFERENCES v3_catalog.channels(id),
    parent_run_id text,
    level text NOT NULL,
    trigger text NOT NULL,
    status text NOT NULL,
    results jsonb NOT NULL DEFAULT '{}',
    started_at timestamptz NOT NULL,
    completed_at timestamptz,
    created_at timestamptz NOT NULL
);
CREATE TABLE v3_channelmarket.ranking_snapshots (
    id text PRIMARY KEY,
    group_id text NOT NULL REFERENCES v3_channelmarket.groups(id),
    window_hours integer NOT NULL,
    ranking_version text NOT NULL,
    rank integer NOT NULL,
    score double precision NOT NULL DEFAULT 0,
    raw_success_rate double precision NOT NULL DEFAULT 0,
    wilson_success_rate double precision NOT NULL DEFAULT 0,
    avg_ttft_ms double precision NOT NULL DEFAULT 0,
    attempt_ttft_p50_ms double precision NOT NULL DEFAULT 0,
    attempt_ttft_p95_ms double precision NOT NULL DEFAULT 0,
    e2e_ttft_p50_ms double precision NOT NULL DEFAULT 0,
    e2e_ttft_p95_ms double precision NOT NULL DEFAULT 0,
    latency_sample_count bigint NOT NULL DEFAULT 0,
    avg_latency_ms double precision NOT NULL DEFAULT 0,
    avg_tps double precision NOT NULL DEFAULT 0,
    cache_hit_rate double precision NOT NULL DEFAULT 0,
    avg_consumer_micro bigint NOT NULL DEFAULT 0,
    avg_consumer_micro_by_model jsonb NOT NULL DEFAULT '{}',
    request_count bigint NOT NULL DEFAULT 0,
    independent_consumers bigint NOT NULL DEFAULT 0,
    observing boolean NOT NULL DEFAULT false,
    calculated_at timestamptz NOT NULL,
    UNIQUE(group_id,window_hours,ranking_version)
);
CREATE TABLE v3_channelmarket.multiplier_trend_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id text NOT NULL REFERENCES v3_channelmarket.groups(id),
    channel_id bigint NOT NULL REFERENCES v3_catalog.channels(id),
    source_label text NOT NULL,
    models jsonb NOT NULL DEFAULT '[]',
    multiplier_ppm bigint NOT NULL,
    reliable boolean NOT NULL DEFAULT false,
    request_count bigint NOT NULL DEFAULT 0,
    wilson_success_rate double precision NOT NULL DEFAULT 0,
    bucket_started_at timestamptz NOT NULL,
    captured_at timestamptz NOT NULL,
    UNIQUE(group_id,bucket_started_at)
);

CREATE TRIGGER channelmarket_groups_touch BEFORE UPDATE ON v3_channelmarket.groups FOR EACH ROW EXECUTE FUNCTION v3_platform.touch_updated_at();
CREATE TRIGGER channelmarket_pools_touch BEFORE UPDATE ON v3_channelmarket.route_pools FOR EACH ROW EXECUTE FUNCTION v3_platform.touch_updated_at();
CREATE TRIGGER channelmarket_groups_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_channelmarket.groups FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('catalog','id');
CREATE TRIGGER channelmarket_access_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_channelmarket.group_access FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('catalog','group_id');
CREATE TRIGGER channelmarket_blocks_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_channelmarket.channel_user_blocks FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('catalog','channel_id');
CREATE TRIGGER channelmarket_multipliers_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_channelmarket.user_multipliers FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('catalog','channel_id');
CREATE TRIGGER channelmarket_windows_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_channelmarket.time_range_multipliers FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('catalog','channel_id');
CREATE TRIGGER channelmarket_pools_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_channelmarket.route_pools FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('catalog','id');
