-- Root-reviewed complex legacy entitlement valuations. Accepted quotes retain
-- each source and revenue basis rather than merging supplemental orders.
CREATE TABLE v3_commerce.subscription_wallet_reviews (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 subscription_id bigint NOT NULL UNIQUE REFERENCES v3_commerce.subscriptions(id),
 fact_hash text NOT NULL CHECK(length(fact_hash)=64),
 revision bigint NOT NULL DEFAULT 1 CHECK(revision>0),
 segments jsonb NOT NULL CHECK(jsonb_typeof(segments)='array' AND jsonb_array_length(segments)>0),
 note text NOT NULL CHECK(length(note) BETWEEN 1 AND 2000),
 enabled boolean NOT NULL DEFAULT false, reviewed boolean NOT NULL DEFAULT false,
 reviewer_id bigint NOT NULL REFERENCES v3_identity.users(id),
 reviewed_at timestamptz NOT NULL,
 CHECK(NOT enabled OR reviewed)
);
CREATE TABLE v3_commerce.subscription_wallet_review_versions (
 review_id bigint NOT NULL REFERENCES v3_commerce.subscription_wallet_reviews(id),
 revision bigint NOT NULL CHECK(revision>0),
 review_snapshot jsonb NOT NULL CHECK(jsonb_typeof(review_snapshot)='object'),
 fact_snapshot jsonb NOT NULL CHECK(jsonb_typeof(fact_snapshot)='object'),
 PRIMARY KEY(review_id,revision)
);
ALTER TABLE v3_commerce.subscription_wallet_quotes
 ALTER COLUMN rule_id DROP NOT NULL,
 ADD COLUMN review_id bigint REFERENCES v3_commerce.subscription_wallet_reviews(id),
 ADD COLUMN segments jsonb NOT NULL DEFAULT '[]',
 ADD COLUMN future_credits bigint NOT NULL DEFAULT 0 CHECK(future_credits>=0),
 ADD CONSTRAINT wallet_quote_basis CHECK((rule_id IS NOT NULL)<>(review_id IS NOT NULL));
ALTER TABLE v3_commerce.subscription_wallet_quotes DROP CONSTRAINT subscription_wallet_quotes_source_credits_check;
ALTER TABLE v3_commerce.subscription_wallet_quotes ADD CHECK(source_credits>=0 AND source_credits+future_credits>0);
ALTER TABLE v3_commerce.subscription_wallet_conversions DROP CONSTRAINT subscription_wallet_conversions_source_credits_check;
ALTER TABLE v3_commerce.subscription_wallet_conversions ADD CHECK(source_credits>=0);
