-- Desktop grants are independently revocable and do not create browser sessions.
CREATE TABLE v3_identity.desktop_devices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    device_name text NOT NULL,
    platform text NOT NULL DEFAULT '',
    app_version text NOT NULL DEFAULT '',
    token_hash bytea NOT NULL UNIQUE CHECK (octet_length(token_hash)=32),
    token_ciphertext bytea NOT NULL,
    scopes text[] NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz
);
CREATE INDEX desktop_devices_user_idx ON v3_identity.desktop_devices(user_id,id DESC);
CREATE TABLE v3_identity.desktop_auth_sessions (
    session_hash bytea PRIMARY KEY CHECK (octet_length(session_hash)=32),
    user_code text NOT NULL,
    device_name text NOT NULL,
    platform text NOT NULL DEFAULT '',
    app_version text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','expired')),
    user_id bigint REFERENCES v3_identity.users(id),
    device_id bigint REFERENCES v3_identity.desktop_devices(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    approved_at timestamptz
);
CREATE TABLE v3_identity.desktop_imports (
    code_hash bytea PRIMARY KEY CHECK (octet_length(code_hash)=32),
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    key_id bigint NOT NULL REFERENCES v3_identity.api_keys(id),
    ciphertext bytea NOT NULL,
    expires_at timestamptz NOT NULL
);
CREATE TABLE v3_identity.desktop_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    device_id bigint NOT NULL REFERENCES v3_identity.desktop_devices(id),
    kind text NOT NULL CHECK (kind IN ('diagnostic','telemetry')),
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX desktop_reports_user_idx ON v3_identity.desktop_reports(user_id,id DESC);
