-- Mailbox recovery must identify one live account, including simultaneous binding/registration.
CREATE UNIQUE INDEX users_live_email_unique ON v3_identity.users (lower(btrim(email)))
    WHERE deleted_at IS NULL AND NULLIF(btrim(email), '') IS NOT NULL;
CREATE TABLE v3_identity.two_factor (
    user_id bigint PRIMARY KEY REFERENCES v3_identity.users(id) ON DELETE CASCADE,
    secret_ciphertext bytea NOT NULL,
    enabled boolean NOT NULL DEFAULT false,
    failed_attempts integer NOT NULL DEFAULT 0 CHECK (failed_attempts >= 0),
    locked_until timestamptz,
    last_counter bigint NOT NULL DEFAULT -1 CHECK (last_counter >= -1),
    last_used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (octet_length(secret_ciphertext) >= 28)
);
CREATE TABLE v3_identity.two_factor_backup_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES v3_identity.two_factor(user_id) ON DELETE CASCADE,
    code_hash text NOT NULL,
    used_at timestamptz,
    CHECK (length(code_hash) BETWEEN 59 AND 60)
);
CREATE INDEX two_factor_backup_unused ON v3_identity.two_factor_backup_codes(user_id) WHERE used_at IS NULL;
CREATE TABLE v3_identity.login_challenges (
    token_hash bytea PRIMARY KEY CHECK (octet_length(token_hash) = 32),
    user_id bigint NOT NULL REFERENCES v3_identity.users(id) ON DELETE CASCADE,
    expires_at timestamptz NOT NULL
);
CREATE INDEX login_challenges_user ON v3_identity.login_challenges(user_id);
CREATE TABLE v3_identity.email_challenges (
    email text NOT NULL CHECK (length(email) BETWEEN 3 AND 254),
    purpose text NOT NULL CHECK (purpose IN ('registration', 'binding', 'reset')),
    user_id bigint REFERENCES v3_identity.users(id) ON DELETE CASCADE,
    token_hash bytea NOT NULL CHECK (octet_length(token_hash) = 32),
    expires_at timestamptz NOT NULL,
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 5),
    state text NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'active')),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (email, purpose),
    CHECK ((purpose = 'registration' AND user_id IS NULL) OR (purpose <> 'registration' AND user_id IS NOT NULL))
);
