CREATE SCHEMA IF NOT EXISTS v3_marketplace;

CREATE TABLE v3_marketplace.group_buys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initiator_id bigint NOT NULL REFERENCES v3_identity.users(id),
    plan_id bigint NOT NULL,
    target_count integer NOT NULL CHECK(target_count BETWEEN 2 AND 1000),
    current_count integer NOT NULL DEFAULT 1 CHECK(current_count>0 AND current_count<=target_count),
    bonus_micro bigint NOT NULL CHECK(bonus_micro>=0),
    bonus_at_2_micro bigint NOT NULL DEFAULT 0 CHECK(bonus_at_2_micro>=0),
    bonus_at_3_micro bigint NOT NULL DEFAULT 0 CHECK(bonus_at_3_micro>=0),
    bonus_at_5_micro bigint NOT NULL DEFAULT 0 CHECK(bonus_at_5_micro>=0),
    expires_at timestamptz NOT NULL,
    settled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','completed','expired')),
    CHECK((status='pending')=(settled_at IS NULL))
);
CREATE INDEX group_buys_pending_idx ON v3_marketplace.group_buys(expires_at,id) WHERE status='pending';
CREATE TABLE v3_marketplace.group_buy_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_buy_id bigint NOT NULL REFERENCES v3_marketplace.group_buys(id),
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    account_id bigint REFERENCES v3_billing.accounts(id),
    order_id bigint NOT NULL DEFAULT 0,
    subscription_id bigint,
    bonus_granted boolean NOT NULL DEFAULT false,
    bonus_amount_micro bigint NOT NULL DEFAULT 0 CHECK(bonus_amount_micro>=0),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(group_buy_id,user_id)
);
CREATE INDEX group_members_user_idx ON v3_marketplace.group_buy_members(user_id,group_buy_id DESC);
CREATE UNIQUE INDEX group_members_paid_order_idx ON v3_marketplace.group_buy_members(order_id) WHERE order_id>0;

CREATE TABLE v3_marketplace.blind_box_pools (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_micro bigint NOT NULL CHECK(price_micro>0),
    daily_limit integer NOT NULL CHECK(daily_limit BETWEEN 1 AND 10000),
    enabled boolean NOT NULL DEFAULT false,
    name text NOT NULL CHECK(name<>''),
    rewards jsonb NOT NULL CHECK(jsonb_typeof(rewards)='array' AND jsonb_array_length(rewards)>0),
    guarantees jsonb NOT NULL DEFAULT '{}',
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE v3_marketplace.blind_box_purchases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    pool_id bigint NOT NULL REFERENCES v3_marketplace.blind_box_pools(id),
    quantity integer NOT NULL CHECK(quantity>0),
    unit_price_micro bigint NOT NULL CHECK(unit_price_micro>=0),
    is_grant boolean NOT NULL DEFAULT false,
    purchase_date date NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    request_id text NOT NULL,
    UNIQUE(user_id,request_id)
);
CREATE INDEX blind_box_purchase_day_idx ON v3_marketplace.blind_box_purchases(user_id,purchase_date);
CREATE TABLE v3_marketplace.blind_box_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id bigint NOT NULL REFERENCES v3_marketplace.blind_box_purchases(id),
    owner_user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    pool_id bigint NOT NULL REFERENCES v3_marketplace.blind_box_pools(id),
    rewards jsonb NOT NULL CHECK(jsonb_typeof(rewards)='array'),
    guarantees jsonb NOT NULL DEFAULT '{}',
    opened_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    status text NOT NULL DEFAULT 'available' CHECK(status IN('available','opened','revoked')),
    CHECK((status='opened')=(opened_at IS NOT NULL))
);
CREATE INDEX blind_box_inventory_idx ON v3_marketplace.blind_box_items(owner_user_id,id) WHERE status='available';
CREATE TABLE v3_marketplace.blind_box_open_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id bigint UNIQUE REFERENCES v3_marketplace.blind_box_items(id) DEFERRABLE INITIALLY DEFERRED,
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    request_id text NOT NULL,
    reward jsonb NOT NULL,
    guarantee_type text NOT NULL DEFAULT 'none' CHECK(guarantee_type IN('none','first','small','big')),
    UNIQUE(user_id,request_id)
);
CREATE INDEX blind_box_history_idx ON v3_marketplace.blind_box_open_records(user_id,id DESC);
CREATE TABLE v3_marketplace.blind_box_pity (
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    pool_id bigint NOT NULL REFERENCES v3_marketplace.blind_box_pools(id),
    opened bigint NOT NULL DEFAULT 0 CHECK(opened>=0),
    small_progress integer NOT NULL DEFAULT 0 CHECK(small_progress>=0),
    big_progress integer NOT NULL DEFAULT 0 CHECK(big_progress>=0),
    PRIMARY KEY(user_id,pool_id)
);
CREATE TABLE v3_marketplace.blind_box_props (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    open_record_id bigint NOT NULL UNIQUE REFERENCES v3_marketplace.blind_box_open_records(id),
    multiplier_ppm bigint CHECK(multiplier_ppm BETWEEN 0 AND 1000000),
    duration_seconds bigint NOT NULL DEFAULT 0 CHECK(duration_seconds>=0),
    remaining_seconds bigint NOT NULL DEFAULT 0 CHECK(remaining_seconds>=0),
    plan_id bigint,
    started_at timestamptz,
    expires_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    kind text NOT NULL CHECK(kind IN('multiplier','subscription','topup_discount','subscription_discount','extra_draw')),
    title text NOT NULL,
    status text NOT NULL DEFAULT 'available' CHECK(status IN('available','active','paused','reserved','used','expired')),
    CHECK(kind<>'multiplier' OR multiplier_ppm IS NOT NULL),
    CHECK(kind<>'subscription' OR plan_id IS NOT NULL)
);
CREATE INDEX blind_box_props_user_idx ON v3_marketplace.blind_box_props(user_id,id DESC);
CREATE TABLE v3_marketplace.account_profiles (
    user_id bigint PRIMARY KEY REFERENCES v3_identity.users(id),
    multiplier_ppm bigint NOT NULL CHECK(multiplier_ppm BETWEEN 0 AND 1000000),
    expires_at timestamptz,
    cards jsonb NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(cards)='array'),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE v3_marketplace.operations (
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    kind text NOT NULL,
    request_id text NOT NULL CHECK(length(request_id) BETWEEN 1 AND 64),
    fingerprint bytea NOT NULL CHECK(octet_length(fingerprint)=32),
    response jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(user_id,kind,request_id)
);
CREATE TRIGGER marketplace_profile_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_marketplace.account_profiles
FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('account_profile','user_id');
