-- Payment credentials never contain plaintext. An unset credential can retain
-- first-setup authentication failures so the account-password check is bounded.
CREATE TABLE v3_commerce.wallet_transfer_security (
    user_id bigint PRIMARY KEY REFERENCES v3_identity.users(id),
    password_hash text,
    failed_attempts integer NOT NULL DEFAULT 0 CHECK(failed_attempts BETWEEN 0 AND 4),
    locked_until timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Snapshots retain the exact fee and participant display data after profile
-- changes. Amounts are integer micro-credits, including imported v2 history.
CREATE TABLE v3_commerce.wallet_transfers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    recipient_user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    amount bigint NOT NULL CHECK(amount>0),
    fee bigint NOT NULL CHECK(fee>=0),
    total_debit bigint NOT NULL CHECK(total_debit>0 AND total_debit-amount=fee),
    sender_balance_after bigint NOT NULL,
    recipient_balance_after bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    request_id text NOT NULL UNIQUE CHECK(length(request_id) BETWEEN 1 AND 128),
    sender_external_id text NOT NULL,
    recipient_external_id text NOT NULL,
    sender_display_name_masked text NOT NULL,
    recipient_display_name_masked text NOT NULL,
    status text NOT NULL DEFAULT 'completed' CHECK(status='completed'),
    CHECK(sender_user_id<>recipient_user_id)
);
CREATE INDEX wallet_transfers_sender_idx ON v3_commerce.wallet_transfers(sender_user_id,id DESC);
CREATE INDEX wallet_transfers_recipient_idx ON v3_commerce.wallet_transfers(recipient_user_id,id DESC);
