-- Commercial state transitions and ledger movements share one transaction.
CREATE SCHEMA IF NOT EXISTS v3_commerce;

CREATE TABLE v3_commerce.plans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    price_minor bigint NOT NULL CHECK (price_minor > 0),
    currency text NOT NULL DEFAULT 'usd' CHECK (currency ~ '^[a-z]{3}$'),
    credits bigint NOT NULL CHECK (credits > 0),
    period_seconds bigint NOT NULL CHECK (period_seconds BETWEEN 60 AND 31622400),
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE v3_commerce.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    plan_id bigint REFERENCES v3_commerce.plans(id),
    amount_minor bigint NOT NULL CHECK (amount_minor > 0),
    credits bigint NOT NULL CHECK (credits > 0),
    period_seconds bigint NOT NULL DEFAULT 0,
    currency text NOT NULL CHECK (currency ~ '^[a-z]{3}$'),
    kind text NOT NULL CHECK (kind IN ('topup','subscription')),
    provider text NOT NULL,
    trade_no text NOT NULL UNIQUE,
    state text NOT NULL DEFAULT 'created' CHECK (state IN ('created','paid','canceled','expired','failed','refunded')),
    provider_reference text,
    payment_url text NOT NULL DEFAULT '',
    payment_event_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    paid_at timestamptz,
    refunded_at timestamptz,
    CHECK ((kind = 'subscription') = (plan_id IS NOT NULL)),
    CHECK ((kind = 'subscription') = (period_seconds > 0))
);
CREATE INDEX orders_user_idx ON v3_commerce.orders(user_id,id DESC);
CREATE INDEX orders_created_expiry_idx ON v3_commerce.orders(expires_at) WHERE state = 'created';
CREATE UNIQUE INDEX orders_provider_reference_idx ON v3_commerce.orders(provider,provider_reference)
    WHERE provider_reference IS NOT NULL;

CREATE TABLE v3_commerce.payment_events (
    provider text NOT NULL,
    event_id text NOT NULL,
    trade_no text NOT NULL REFERENCES v3_commerce.orders(trade_no),
    fingerprint bytea NOT NULL CHECK (octet_length(fingerprint) = 32),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(provider,event_id)
);

CREATE TABLE v3_commerce.subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    plan_id bigint NOT NULL REFERENCES v3_commerce.plans(id),
    account_id bigint REFERENCES v3_billing.accounts(id),
    order_id bigint UNIQUE REFERENCES v3_commerce.orders(id),
    state text NOT NULL DEFAULT 'active' CHECK (state IN ('active','expired','canceled')),
    starts_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL CHECK (expires_at > starts_at),
    ended_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX subscriptions_user_idx ON v3_commerce.subscriptions(user_id,expires_at)
    WHERE state = 'active';
CREATE INDEX subscriptions_expiry_idx ON v3_commerce.subscriptions(expires_at)
    WHERE state = 'active';

CREATE TRIGGER plans_touch BEFORE UPDATE ON v3_commerce.plans
    FOR EACH ROW EXECUTE FUNCTION v3_platform.touch_updated_at();
CREATE TRIGGER subscriptions_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_commerce.subscriptions
    FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('user', 'user_id');
