-- Retained model/vendor metadata and reusable configuration groups. Imported
-- identities and soft deletions remain intact; mutations invalidate snapshots.
CREATE TABLE v3_catalog.vendors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL CHECK (btrim(name) <> ''),
    description text NOT NULL DEFAULT '',
    icon text NOT NULL DEFAULT '',
    status integer NOT NULL DEFAULT 1 CHECK (status >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
CREATE UNIQUE INDEX vendors_live_name ON v3_catalog.vendors(name) WHERE deleted_at IS NULL;

CREATE TABLE v3_catalog.models (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name text NOT NULL CHECK (btrim(model_name) <> ''),
    description text NOT NULL DEFAULT '',
    icon text NOT NULL DEFAULT '',
    tags text NOT NULL DEFAULT '',
    endpoints text NOT NULL DEFAULT '',
    vendor_id bigint REFERENCES v3_catalog.vendors(id),
    status integer NOT NULL DEFAULT 1 CHECK (status >= 0),
    sync_official integer NOT NULL DEFAULT 1 CHECK (sync_official >= 0),
    name_rule integer NOT NULL DEFAULT 0 CHECK (name_rule BETWEEN 0 AND 3),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
CREATE UNIQUE INDEX models_live_name ON v3_catalog.models(model_name) WHERE deleted_at IS NULL;
CREATE INDEX models_vendor ON v3_catalog.models(vendor_id) WHERE deleted_at IS NULL;

CREATE TABLE v3_catalog.prefill_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL CHECK (btrim(name) <> ''),
    type text NOT NULL CHECK (type IN ('model','tag','endpoint')),
    description text NOT NULL DEFAULT '',
    items jsonb NOT NULL DEFAULT '[]',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CHECK ((type IN ('model','tag') AND jsonb_typeof(items) = 'array'
            AND NOT jsonb_path_exists(items, '$[*] ? (@.type() != "string" || @ == "")'))
        OR (type = 'endpoint' AND jsonb_typeof(items) IN ('array','object')))
);
CREATE UNIQUE INDEX prefill_groups_live_name ON v3_catalog.prefill_groups(name) WHERE deleted_at IS NULL;

CREATE TRIGGER vendors_touch BEFORE UPDATE ON v3_catalog.vendors
    FOR EACH ROW EXECUTE FUNCTION v3_platform.touch_updated_at();
CREATE TRIGGER models_touch BEFORE UPDATE ON v3_catalog.models
    FOR EACH ROW EXECUTE FUNCTION v3_platform.touch_updated_at();
CREATE TRIGGER prefill_groups_touch BEFORE UPDATE ON v3_catalog.prefill_groups
    FOR EACH ROW EXECUTE FUNCTION v3_platform.touch_updated_at();
CREATE TRIGGER vendors_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_catalog.vendors
    FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('catalog','id');
CREATE TRIGGER models_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_catalog.models
    FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('catalog','id');
CREATE TRIGGER prefill_groups_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_catalog.prefill_groups
    FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('catalog','id');
