-- Groups, channels, credentials, model routing and prices. The control plane
-- compiles these into an immutable snapshot; gateways never query them per
-- request (plan §3).

CREATE TABLE v3_catalog.groups (
    name        text           PRIMARY KEY,
    description text           NOT NULL DEFAULT '',
    multiplier  numeric(10, 4) NOT NULL DEFAULT 1 CHECK (multiplier >= 0),
    created_at  timestamptz    NOT NULL DEFAULT now(),
    updated_at  timestamptz    NOT NULL DEFAULT now()
);

CREATE TABLE v3_catalog.channels (
    id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- v2 ids preserved
    name            text        NOT NULL,
    provider        text        NOT NULL,              -- adapter id, e.g. 'openai', 'claude', 'gemini'
    base_url        text        NOT NULL DEFAULT '',
    proxy_url       text        NOT NULL DEFAULT '',    -- http(s)/socks5 egress proxy, '' = direct
    status          text        NOT NULL DEFAULT 'enabled'
                                CHECK (status IN ('enabled', 'disabled', 'auto_disabled')),
    scope           text        NOT NULL DEFAULT 'official' CHECK (scope IN ('official', 'marketplace')),
    owner_user_id   bigint      REFERENCES v3_identity.users (id), -- marketplace channel owner
    priority        integer     NOT NULL DEFAULT 0,
    weight          integer     NOT NULL DEFAULT 0 CHECK (weight >= 0),
    max_concurrency      integer NOT NULL DEFAULT 0 CHECK (max_concurrency >= 0),      -- 0 = unlimited
    max_user_concurrency integer NOT NULL DEFAULT 0 CHECK (max_user_concurrency >= 0),
    auto_disable    boolean     NOT NULL DEFAULT true,
    multiplier_card_supported boolean NOT NULL DEFAULT false,
    model_mapping   jsonb       NOT NULL DEFAULT '{}',  -- requested model -> upstream model
    param_override  jsonb       NOT NULL DEFAULT '{}',
    header_override jsonb       NOT NULL DEFAULT '{}',
    status_code_mapping jsonb   NOT NULL DEFAULT '{}',
    settings        jsonb       NOT NULL DEFAULT '{}',  -- provider-specific (API version, region, ...)
    tag             text,
    remark          text        NOT NULL DEFAULT '',
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX channels_owner_idx ON v3_catalog.channels (owner_user_id) WHERE owner_user_id IS NOT NULL;

-- v2 stored multiple keys newline-separated in channels.key. Each credential
-- is scheduled, cooled down and refreshed on its own (plan §3 scheduler).
CREATE TABLE v3_catalog.channel_credentials (
    id           bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    channel_id   bigint      NOT NULL REFERENCES v3_catalog.channels (id) ON DELETE CASCADE,
    kind         text        NOT NULL DEFAULT 'api_key' CHECK (kind IN ('api_key', 'oauth')),
    secret       bytea       NOT NULL,                  -- AES-GCM ciphertext
    status       text        NOT NULL DEFAULT 'enabled' CHECK (status IN ('enabled', 'disabled')),
    expires_at   timestamptz,                          -- OAuth access token expiry, drives refresh heap
    fingerprint  jsonb       NOT NULL DEFAULT '{}',     -- cached client identity (UA, client id)
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX channel_credentials_channel_idx ON v3_catalog.channel_credentials (channel_id);
CREATE INDEX channel_credentials_expiry_idx
    ON v3_catalog.channel_credentials (expires_at) WHERE kind = 'oauth' AND status = 'enabled';

CREATE TABLE v3_catalog.channel_groups (
    channel_id bigint NOT NULL REFERENCES v3_catalog.channels (id) ON DELETE CASCADE,
    group_name text   NOT NULL REFERENCES v3_catalog.groups (name) ON UPDATE CASCADE,
    PRIMARY KEY (channel_id, group_name)
);

CREATE TABLE v3_catalog.channel_models (
    channel_id bigint NOT NULL REFERENCES v3_catalog.channels (id) ON DELETE CASCADE,
    model      text   NOT NULL,
    PRIMARY KEY (channel_id, model)
);

CREATE INDEX channel_models_model_idx ON v3_catalog.channel_models (model);

-- Prices are absolute micro-credits, not v2's ratio-of-a-ratio. Tiered and
-- expression pricing are stored in rules and evaluated by the pricing engine.
CREATE TABLE v3_catalog.model_prices (
    model                    text        PRIMARY KEY,
    mode                     text        NOT NULL DEFAULT 'per_token'
                                         CHECK (mode IN ('per_token', 'per_request', 'expression')),
    input_per_mtok           bigint      NOT NULL DEFAULT 0 CHECK (input_per_mtok >= 0),
    output_per_mtok          bigint      NOT NULL DEFAULT 0 CHECK (output_per_mtok >= 0),
    cache_read_per_mtok      bigint      NOT NULL DEFAULT 0 CHECK (cache_read_per_mtok >= 0),
    cache_write_per_mtok     bigint      NOT NULL DEFAULT 0 CHECK (cache_write_per_mtok >= 0),
    per_request              bigint      NOT NULL DEFAULT 0 CHECK (per_request >= 0),
    rules                    jsonb       NOT NULL DEFAULT '{}', -- tiers / expression / tool prices
    updated_at               timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE v3_catalog.route_pools (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name text        NOT NULL REFERENCES v3_catalog.groups (name) ON UPDATE CASCADE,
    model      text        NOT NULL,                    -- '*' matches every model in the group
    strategy   text        NOT NULL DEFAULT 'weighted'
                           CHECK (strategy IN ('round_robin', 'fill_first', 'weighted')),
    enabled    boolean     NOT NULL DEFAULT true,
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (group_name, model)
);

CREATE TABLE v3_catalog.route_pool_members (
    pool_id    bigint  NOT NULL REFERENCES v3_catalog.route_pools (id) ON DELETE CASCADE,
    channel_id bigint  NOT NULL REFERENCES v3_catalog.channels (id) ON DELETE CASCADE,
    priority   integer NOT NULL DEFAULT 0,
    weight     integer NOT NULL DEFAULT 1 CHECK (weight > 0),
    PRIMARY KEY (pool_id, channel_id)
);

CREATE TRIGGER groups_touch BEFORE UPDATE ON v3_catalog.groups
    FOR EACH ROW EXECUTE FUNCTION v3_platform.touch_updated_at();
CREATE TRIGGER channels_touch BEFORE UPDATE ON v3_catalog.channels
    FOR EACH ROW EXECUTE FUNCTION v3_platform.touch_updated_at();
CREATE TRIGGER channel_credentials_touch BEFORE UPDATE ON v3_catalog.channel_credentials
    FOR EACH ROW EXECUTE FUNCTION v3_platform.touch_updated_at();
CREATE TRIGGER model_prices_touch BEFORE UPDATE ON v3_catalog.model_prices
    FOR EACH ROW EXECUTE FUNCTION v3_platform.touch_updated_at();
CREATE TRIGGER route_pools_touch BEFORE UPDATE ON v3_catalog.route_pools
    FOR EACH ROW EXECUTE FUNCTION v3_platform.touch_updated_at();

-- Any catalog change schedules a snapshot rebuild; the entity id is informational.
CREATE TRIGGER groups_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_catalog.groups
    FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('catalog', 'name');
CREATE TRIGGER channels_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_catalog.channels
    FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('catalog', 'id');
CREATE TRIGGER channel_credentials_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_catalog.channel_credentials
    FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('catalog', 'channel_id');
CREATE TRIGGER channel_groups_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_catalog.channel_groups
    FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('catalog', 'channel_id');
CREATE TRIGGER channel_models_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_catalog.channel_models
    FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('catalog', 'channel_id');
CREATE TRIGGER model_prices_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_catalog.model_prices
    FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('pricing', 'model');
CREATE TRIGGER route_pools_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_catalog.route_pools
    FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('catalog', 'id');
CREATE TRIGGER route_pool_members_invalidate AFTER INSERT OR UPDATE OR DELETE ON v3_catalog.route_pool_members
    FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('catalog', 'pool_id');
