CREATE TABLE v3_commerce.redemption_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash bytea NOT NULL UNIQUE CHECK (octet_length(code_hash)=32),
    name text NOT NULL DEFAULT '',
    credits bigint NOT NULL CHECK (credits>0),
    state text NOT NULL DEFAULT 'active' CHECK (state IN ('active','used','revoked')),
    claimed_by bigint REFERENCES v3_identity.users(id),
    expires_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    claimed_at timestamptz,
    CHECK ((state='used')=(claimed_by IS NOT NULL AND claimed_at IS NOT NULL))
);
CREATE INDEX redemption_codes_created_idx ON v3_commerce.redemption_codes(id DESC);
