-- Retained marketplace state is typed and remains consumable after an offline
-- import. External cash orders and wallet purchases have independent IDs.
ALTER TABLE v3_marketplace.blind_box_pools ADD COLUMN scope text NOT NULL DEFAULT 'credits'
    CHECK(scope IN('standard','credits'));
ALTER TABLE v3_marketplace.blind_box_pools
    ADD COLUMN monthly_limit integer NOT NULL DEFAULT 0 CHECK(monthly_limit>=0),
    ADD COLUMN daily_open_limit integer NOT NULL DEFAULT 0 CHECK(daily_open_limit>=0),
    ADD COLUMN standard_policy jsonb NOT NULL DEFAULT '{}';
ALTER TABLE v3_marketplace.blind_box_purchases
    ADD COLUMN total_micro bigint NOT NULL DEFAULT 0 CHECK(total_micro>=0),
    ADD COLUMN status text NOT NULL DEFAULT 'completed' CHECK(status IN('completed','revoked'));
CREATE TABLE v3_marketplace.blind_box_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    pool_id bigint REFERENCES v3_marketplace.blind_box_pools(id),
    quantity integer NOT NULL CHECK(quantity>0),
    opened_count integer NOT NULL DEFAULT 0 CHECK(opened_count>=0 AND opened_count<=quantity),
    amount_minor bigint NOT NULL DEFAULT 0 CHECK(amount_minor>=0),
    subscription_id bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    expires_at timestamptz,
    trade_no text NOT NULL UNIQUE,
    payment_provider text NOT NULL DEFAULT '',
    payment_method text NOT NULL DEFAULT '',
    currency text NOT NULL DEFAULT 'usd',
    source text NOT NULL DEFAULT 'purchase',
    benefit_cycle text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','success','completed','cancelled','canceled','expired','failed','refunded','revoked')),
    provider_payload jsonb NOT NULL DEFAULT '{}'
);
ALTER TABLE v3_marketplace.blind_box_purchases ADD COLUMN external_order_id bigint UNIQUE REFERENCES v3_marketplace.blind_box_orders(id);
ALTER TABLE v3_marketplace.blind_box_items
    ADD COLUMN pool_version text NOT NULL DEFAULT 'v3-open-draw',
    ADD COLUMN purchase_user_id bigint REFERENCES v3_identity.users(id),
    ADD COLUMN frozen_reward jsonb,
    ADD COLUMN draw_current_pool boolean NOT NULL DEFAULT true,
    ADD COLUMN reward_tier text NOT NULL DEFAULT '',
    ADD COLUMN reward_wallet_type text NOT NULL DEFAULT '',
    ADD COLUMN guarantee_type text NOT NULL DEFAULT 'none',
    ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(),
    ADD COLUMN expires_at timestamptz,
    ADD COLUMN open_record_id bigint REFERENCES v3_marketplace.blind_box_open_records(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE v3_marketplace.blind_box_open_records
    ADD COLUMN order_id bigint REFERENCES v3_marketplace.blind_box_orders(id),
    ADD COLUMN pool_id bigint REFERENCES v3_marketplace.blind_box_pools(id),
    ADD COLUMN reward_tier text NOT NULL DEFAULT '',
    ADD COLUMN reward_wallet_type text NOT NULL DEFAULT '',
    ADD COLUMN subscription_id bigint,
    ADD COLUMN pool_type text NOT NULL DEFAULT '',
    ADD COLUMN is_pity boolean NOT NULL DEFAULT false;
ALTER TABLE v3_marketplace.blind_box_pity
    ADD COLUMN legacy_id bigint,
    ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE v3_marketplace.blind_box_props
    ADD COLUMN prop_type text NOT NULL DEFAULT '',
    ADD COLUMN discount_rate_ppm bigint NOT NULL DEFAULT 0 CHECK(discount_rate_ppm BETWEEN 0 AND 1000000),
    ADD COLUMN max_discount_micro bigint NOT NULL DEFAULT 0 CHECK(max_discount_micro>=0),
    ADD COLUMN used_discount_micro bigint NOT NULL DEFAULT 0 CHECK(used_discount_micro>=0),
    ADD COLUMN reserved_at timestamptz,
    ADD COLUMN reserved_order_type text NOT NULL DEFAULT '',
    ADD COLUMN reserved_order_trade_no text NOT NULL DEFAULT '',
    ADD COLUMN used_at timestamptz,
    ADD COLUMN benefit_reference text NOT NULL DEFAULT '';
ALTER TABLE v3_marketplace.blind_box_props ALTER COLUMN open_record_id DROP NOT NULL;
CREATE INDEX blind_box_reserved_order_idx ON v3_marketplace.blind_box_props(reserved_order_type,reserved_order_trade_no) WHERE status='reserved';
CREATE TABLE v3_marketplace.blind_box_grants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    admin_user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    blind_box_order_id bigint REFERENCES v3_marketplace.blind_box_orders(id),
    quantity integer NOT NULL CHECK(quantity>0),
    created_at timestamptz NOT NULL DEFAULT now(),
    reason text NOT NULL DEFAULT '',
    idempotency_key text UNIQUE,
    trade_no text NOT NULL UNIQUE
);
CREATE TABLE v3_marketplace.blind_box_prop_gifts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prop_id bigint NOT NULL REFERENCES v3_marketplace.blind_box_props(id),
    sender_user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    recipient_user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    request_id text NOT NULL UNIQUE,
    sender_external_id text NOT NULL DEFAULT '',
    recipient_external_id text NOT NULL DEFAULT '',
    prop_type text NOT NULL DEFAULT '',
    prop_title text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'completed' CHECK(status='completed')
);
CREATE TABLE v3_marketplace.blind_box_prop_discount_usages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    prop_id bigint NOT NULL REFERENCES v3_marketplace.blind_box_props(id),
    channel_id bigint NOT NULL,
    before_micro bigint NOT NULL CHECK(before_micro>=0),
    after_micro bigint NOT NULL CHECK(after_micro>=0 AND after_micro<=before_micro),
    discount_micro bigint NOT NULL CHECK(discount_micro=before_micro-after_micro),
    discount_rate_ppm bigint NOT NULL CHECK(discount_rate_ppm BETWEEN 0 AND 1000000),
    multiplier_ppm bigint NOT NULL CHECK(multiplier_ppm BETWEEN 0 AND 1000000),
    effective_multiplier_ppm bigint NOT NULL CHECK(effective_multiplier_ppm BETWEEN 0 AND 1000000),
    remaining_micro bigint NOT NULL DEFAULT 0 CHECK(remaining_micro>=0),
    created_at timestamptz NOT NULL DEFAULT now(),
    request_id text NOT NULL UNIQUE,
    prop_title text NOT NULL DEFAULT '',
    channel_scope text NOT NULL DEFAULT '',
    model_name text NOT NULL DEFAULT ''
);
CREATE TABLE v3_marketplace.blind_box_gifts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    recipient_user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    quantity integer NOT NULL CHECK(quantity>0),
    created_at timestamptz NOT NULL DEFAULT now(),
    request_id text NOT NULL UNIQUE,
    sender_external_id text NOT NULL DEFAULT '',
    recipient_external_id text NOT NULL DEFAULT '',
    sender_display_name_masked text NOT NULL DEFAULT '',
    recipient_display_name_masked text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'completed' CHECK(status='completed')
);
CREATE TABLE v3_marketplace.blind_box_gift_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gift_id bigint NOT NULL REFERENCES v3_marketplace.blind_box_gifts(id),
    item_id bigint NOT NULL REFERENCES v3_marketplace.blind_box_items(id),
    from_user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    to_user_id bigint NOT NULL REFERENCES v3_identity.users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(gift_id,item_id)
);
CREATE TABLE v3_marketplace.blind_box_zero_hour_states (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE REFERENCES v3_identity.users(id),
    points bigint NOT NULL DEFAULT 0 CHECK(points BETWEEN 0 AND 1000),
    usage_micro bigint NOT NULL DEFAULT 0 CHECK(usage_micro>=0),
    hit_count integer NOT NULL DEFAULT 0 CHECK(hit_count>=0),
    updated_at timestamptz NOT NULL DEFAULT now()
);
