-- Users, external identities and API keys. Balances do not live here: the
-- billing ledger is the only source of truth (plan §5).

CREATE TABLE v3_identity.users (
    id            bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- v2 ids are preserved on migration
    external_id   text        UNIQUE,
    username      text        NOT NULL UNIQUE,
    display_name  text        NOT NULL DEFAULT '',
    email         text,
    password_hash text,                                  -- NULL for OAuth-only accounts
    role          text        NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin', 'root')),
    status        text        NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    group_name    text        NOT NULL DEFAULT 'default',
    inviter_id    bigint      REFERENCES v3_identity.users (id),
    aff_code      text        UNIQUE,
    settings      jsonb       NOT NULL DEFAULT '{}',
    remark        text        NOT NULL DEFAULT '',
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    last_login_at timestamptz,
    deleted_at    timestamptz
);

CREATE INDEX users_email_idx ON v3_identity.users (lower(email)) WHERE email IS NOT NULL;
CREATE INDEX users_inviter_idx ON v3_identity.users (inviter_id) WHERE inviter_id IS NOT NULL;

-- Replaces v2's github_id / discord_id / oidc_id / wechat_id / telegram_id /
-- linux_do_id columns with one row per linked provider.
CREATE TABLE v3_identity.user_identities (
    provider   text        NOT NULL,
    subject    text        NOT NULL,
    user_id    bigint      NOT NULL REFERENCES v3_identity.users (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (provider, subject)
);

CREATE INDEX user_identities_user_idx ON v3_identity.user_identities (user_id);

-- API keys are looked up by SHA-256 of the presented key. The ciphertext keeps
-- the "show key again" feature without storing plaintext.
CREATE TABLE v3_identity.api_keys (
    id                bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           bigint      NOT NULL REFERENCES v3_identity.users (id),
    name              text        NOT NULL DEFAULT '',
    key_hash          bytea       NOT NULL UNIQUE CHECK (octet_length(key_hash) = 32),
    key_prefix        text        NOT NULL,              -- e.g. "sk-ab12" for display
    key_ciphertext    bytea       NOT NULL,              -- AES-GCM, key from KMS/env
    status            text        NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    group_name        text,                              -- NULL inherits the user's group
    cross_group_retry boolean     NOT NULL DEFAULT false,
    allowed_models    text[],                            -- NULL means all models
    allowed_cidrs     cidr[],                            -- NULL means any address
    budget_limited    boolean     NOT NULL DEFAULT false, -- true: spends from its own billing account
    max_marketplace_multiplier numeric(10, 4) NOT NULL DEFAULT 0 CHECK (max_marketplace_multiplier >= 0),
    expires_at        timestamptz,                       -- NULL never expires
    last_used_at      timestamptz,                       -- throttled to one write per 30 s per key
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    deleted_at        timestamptz
);

CREATE INDEX api_keys_user_idx ON v3_identity.api_keys (user_id) WHERE deleted_at IS NULL;

CREATE TRIGGER users_touch BEFORE UPDATE ON v3_identity.users
    FOR EACH ROW EXECUTE FUNCTION v3_platform.touch_updated_at();
CREATE TRIGGER api_keys_touch BEFORE UPDATE ON v3_identity.api_keys
    FOR EACH ROW EXECUTE FUNCTION v3_platform.touch_updated_at();

-- last_used_at churn must not invalidate caches, so only the columns that
-- change authorization results fire the trigger.
CREATE TRIGGER users_invalidate
    AFTER INSERT OR DELETE OR UPDATE OF status, role, group_name, deleted_at ON v3_identity.users
    FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('user', 'id');
CREATE TRIGGER api_keys_invalidate
    AFTER INSERT OR DELETE OR UPDATE OF status, group_name, cross_group_retry, allowed_models,
        allowed_cidrs, budget_limited, max_marketplace_multiplier, expires_at, deleted_at
    ON v3_identity.api_keys
    FOR EACH ROW EXECUTE FUNCTION v3_platform.enqueue_invalidation('api_key', 'id');
