import type { BlindBoxTierSetting } from '@/features/system-settings/types'

const DEFAULT_BALANCE_BLIND_BOX_TIERS: BlindBoxTierSetting[] = [
  {
    name: '$1.00-$3.00 官方 GPT 专属额度',
    min_usd: 1,
    max_usd: 3,
    probability: 0.06,
    reward_type: 'quota',
    wallet_type: 'default',
  },
  {
    name: '$3.00-$6.00 官方 GPT 专属额度',
    min_usd: 3,
    max_usd: 6,
    probability: 0.12,
    reward_type: 'quota',
    wallet_type: 'default',
  },
  {
    name: '$6.00-$10.00 官方 GPT 专属额度',
    min_usd: 6,
    max_usd: 10,
    probability: 0.1,
    reward_type: 'quota',
    wallet_type: 'default',
  },
  {
    name: '$10.00-$15.00 官方 GPT 专属额度',
    min_usd: 10,
    max_usd: 15,
    probability: 0.075,
    reward_type: 'quota',
    wallet_type: 'default',
  },
  {
    name: '$15.00-$20.00 官方 GPT 专属额度',
    min_usd: 15,
    max_usd: 20,
    probability: 0.22,
    reward_type: 'quota',
    wallet_type: 'default',
  },
  {
    name: '$25.00-$40.00 官方 GPT 专属额度',
    min_usd: 25,
    max_usd: 40,
    probability: 0.05,
    reward_type: 'quota',
    wallet_type: 'default',
  },
  {
    name: '$80 官方 GPT 专属额度',
    min_usd: 80,
    max_usd: 80,
    probability: 0.004,
    reward_type: 'quota',
    wallet_type: 'default',
  },
  {
    name: '$200 官方 GPT 专属额度',
    min_usd: 200,
    max_usd: 200,
    probability: 0.00075,
    reward_type: 'quota',
    wallet_type: 'default',
  },
  {
    name: '$500 官方 GPT 专属额度',
    min_usd: 500,
    max_usd: 500,
    probability: 0.00036,
    reward_type: 'quota',
    wallet_type: 'default',
  },
  {
    name: '$5000 官方 GPT 专属额度',
    min_usd: 5000,
    max_usd: 5000,
    probability: 0.00004,
    reward_type: 'quota',
    wallet_type: 'default',
  },
  {
    name: '$2.50-$3.75 通用额度（等值 $10-$15）',
    min_usd: 2.5,
    max_usd: 3.75,
    probability: 0.075,
    reward_type: 'claude_quota',
    wallet_type: 'claude',
  },
  {
    name: '$3.75-$5.00 通用额度（等值 $15-$20）',
    min_usd: 3.75,
    max_usd: 5,
    probability: 0.22,
    reward_type: 'claude_quota',
    wallet_type: 'claude',
  },
  {
    name: '$6.25-$10.00 通用额度（等值 $25-$40）',
    min_usd: 6.25,
    max_usd: 10,
    probability: 0.05,
    reward_type: 'claude_quota',
    wallet_type: 'claude',
  },
  {
    name: '$20 通用额度（等值 $80）',
    min_usd: 20,
    max_usd: 20,
    probability: 0.004,
    reward_type: 'claude_quota',
    wallet_type: 'claude',
  },
  {
    name: '$50 通用额度（等值 $200）',
    min_usd: 50,
    max_usd: 50,
    probability: 0.00075,
    reward_type: 'claude_quota',
    wallet_type: 'claude',
  },
  {
    name: '充值九折卡',
    min_usd: 0,
    max_usd: 0,
    probability: 0.007,
    reward_type: 'prop',
  },
  {
    name: '套餐九折卡',
    min_usd: 0,
    max_usd: 0,
    probability: 0.004,
    reward_type: 'prop',
  },
  {
    name: '0.95 倍率卡',
    min_usd: 0,
    max_usd: 0,
    probability: 0.006,
    reward_type: 'prop',
  },
  {
    name: '0.9 倍率卡',
    min_usd: 0,
    max_usd: 0,
    probability: 0.0031,
    reward_type: 'prop',
  },
]

export const BALANCE_BLIND_BOX_DEFAULTS = {
  'blind_box_setting.balance_blind_box_enabled': true,
  'blind_box_setting.balance_blind_box_price_usd': 15,
  'blind_box_setting.balance_blind_box_daily_purchase_limit': 10,
  'blind_box_setting.balance_blind_box_first_draw_guarantee_usd': 10,
  'blind_box_setting.balance_blind_box_small_pity_threshold': 10,
  'blind_box_setting.balance_blind_box_small_pity_guarantee_usd': 10,
  'blind_box_setting.balance_blind_box_pity_threshold': 50,
  'blind_box_setting.balance_blind_box_pity_guarantee_usd': 35,
  'blind_box_setting.balance_blind_box_tiers': DEFAULT_BALANCE_BLIND_BOX_TIERS,
}
