import type { BlindBoxTierSetting } from '@/features/system-settings/types'

export const DEFAULT_BALANCE_BLIND_BOX_TIERS: BlindBoxTierSetting[] = [
  {
    name: '1.00-1.50 统一额度',
    min_usd: 1,
    max_usd: 1.5,
    probability: 0.4366,
    reward_type: 'claude_quota',
    wallet_type: 'claude',
  },
  {
    name: '1.50-2.00 统一额度',
    min_usd: 1.5,
    max_usd: 2,
    probability: 0.24,
    reward_type: 'claude_quota',
    wallet_type: 'claude',
  },
  {
    name: '2.00-2.80 统一额度',
    min_usd: 2,
    max_usd: 2.8,
    probability: 0.0975,
    reward_type: 'claude_quota',
    wallet_type: 'claude',
  },
  {
    name: '2.80-4.00 统一额度',
    min_usd: 2.8,
    max_usd: 4,
    probability: 0.045,
    reward_type: 'claude_quota',
    wallet_type: 'claude',
  },
  {
    name: '4.00-6.00 统一额度',
    min_usd: 4,
    max_usd: 6,
    probability: 0.02,
    reward_type: 'claude_quota',
    wallet_type: 'claude',
  },
  {
    name: '6.00-10.00 统一额度',
    min_usd: 6,
    max_usd: 10,
    probability: 0.012,
    reward_type: 'claude_quota',
    wallet_type: 'claude',
  },
  {
    name: '10.00-20.00 统一额度',
    min_usd: 10,
    max_usd: 20,
    probability: 0.006,
    reward_type: 'claude_quota',
    wallet_type: 'claude',
  },
  {
    name: '20.00-50.00 统一额度',
    min_usd: 20,
    max_usd: 50,
    probability: 0.002,
    reward_type: 'claude_quota',
    wallet_type: 'claude',
  },
  {
    name: '50.00-200.00 统一额度',
    min_usd: 50,
    max_usd: 200,
    probability: 0.0007,
    reward_type: 'claude_quota',
    wallet_type: 'claude',
  },
  {
    name: '200.00-1000.00 统一额度',
    min_usd: 200,
    max_usd: 1000,
    probability: 0.0002,
    reward_type: 'claude_quota',
    wallet_type: 'claude',
  },
  {
    name: '充值九折卡',
    min_usd: 0,
    max_usd: 0,
    probability: 0.03,
    reward_type: 'prop',
  },
  {
    name: '0.95 倍率卡',
    min_usd: 0,
    max_usd: 0,
    probability: 0.06,
    reward_type: 'prop',
  },
  {
    name: '0.9 倍率卡',
    min_usd: 0,
    max_usd: 0,
    probability: 0.04,
    reward_type: 'prop',
  },
  {
    name: '0.10 倍率体验卡',
    min_usd: 0,
    max_usd: 0,
    probability: 0.01,
    reward_type: 'prop',
  },
]

export const BALANCE_BLIND_BOX_DEFAULTS = {
  'blind_box_setting.balance_blind_box_enabled': true,
  'blind_box_setting.balance_blind_box_price_usd': 2.5,
  'blind_box_setting.balance_blind_box_daily_purchase_limit': 500,
  'blind_box_setting.balance_blind_box_first_draw_guarantee_usd': 10,
  'blind_box_setting.balance_blind_box_small_pity_threshold': 10,
  'blind_box_setting.balance_blind_box_small_pity_guarantee_usd': 10,
  'blind_box_setting.balance_blind_box_pity_threshold': 50,
  'blind_box_setting.balance_blind_box_pity_guarantee_usd': 35,
  'blind_box_setting.balance_blind_box_tiers': DEFAULT_BALANCE_BLIND_BOX_TIERS,
}
