//go:build pgintegration

package legacy

import (
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

const onlineBackupFixture = `
 CREATE TABLE parent(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,amount numeric(30,6) NOT NULL,payload jsonb NOT NULL, doubled numeric GENERATED ALWAYS AS (amount*2) STORED);
 CREATE TABLE child(id bigint PRIMARY KEY,parent_id bigint NOT NULL REFERENCES parent(id));
 CREATE TABLE notes(body text);
 CREATE TABLE retired_accounts(id bigint PRIMARY KEY,payload jsonb NOT NULL);
 CREATE TABLE invoice_requests(id bigint PRIMARY KEY,status text NOT NULL);
 INSERT INTO parent(id,amount,payload) OVERRIDING SYSTEM VALUE VALUES(1,12345678901234567890.123456,'{"large":123456789012345678901234567890}'),(2,2,'{}');
 INSERT INTO child VALUES(1,1);
 INSERT INTO notes VALUES('duplicate'),('duplicate');
 INSERT INTO retired_accounts VALUES(1,'{"keep":true}');
 INSERT INTO invoice_requests VALUES(1,'pending');
 SELECT setval('parent_id_seq',2,true);`

func onlineBackupDBs(t *testing.T) (context.Context, *pgxpool.Pool, *pgxpool.Pool, OnlineDeltaApplyOptions) {
	t.Helper()
	dsn := os.Getenv("V3_MIGRATION_TEST_PG_DSN")
	if dsn == "" {
		t.Skip("V3_MIGRATION_TEST_PG_DSN not set")
	}
	ctx := context.Background()
	source := migrationDatabase(t, dsn, "online_delta_source")
	admin, err := pgx.Connect(ctx, dsn)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = admin.Close(ctx) }()
	random := make([]byte, 8)
	if _, err = rand.Read(random); err != nil {
		t.Fatal(err)
	}
	name := "online_restore_" + hex.EncodeToString(random)
	if _, err = admin.Exec(ctx, "CREATE DATABASE "+pgx.Identifier{name}.Sanitize()); err != nil {
		t.Fatal(err)
	}
	config, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		t.Fatal(err)
	}
	config.ConnConfig.Database = name
	target, err := pgxpool.NewWithConfig(ctx, config)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(target.Close)
	return ctx, source, target, OnlineDeltaApplyOptions{RunID: "online-backup-fixture-20261009", Database: name, SpoolDirectory: t.TempDir()}
}

func onlineBackupDigest(t *testing.T, pool *pgxpool.Pool) string {
	t.Helper()
	var digest string
	if err := pool.QueryRow(context.Background(), `SELECT jsonb_build_object('parent',(SELECT jsonb_agg(to_jsonb(t) ORDER BY id) FROM parent t),'child',(SELECT jsonb_agg(to_jsonb(t) ORDER BY id) FROM child t),'notes',(SELECT jsonb_agg(to_jsonb(t) ORDER BY body) FROM notes t),'retired',(SELECT jsonb_agg(to_jsonb(t) ORDER BY id) FROM retired_accounts t),'invoices',(SELECT jsonb_agg(to_jsonb(t) ORDER BY id) FROM invoice_requests t))::text`).Scan(&digest); err != nil {
		t.Fatal(err)
	}
	return digest
}

func TestOnlineDeltaCompleteReplayAndLateCommit(t *testing.T) {
	ctx, source, target, opts := onlineBackupDBs(t)
	for _, pool := range []*pgxpool.Pool{source, target} {
		if _, err := pool.Exec(ctx, onlineBackupFixture); err != nil {
			t.Fatal(err)
		}
	}
	if _, err := SetupOnlineCapture(ctx, source, opts.RunID, true); err != nil {
		t.Fatal(err)
	}
	// A lower event ID remains uncommitted while a higher one is exported.
	late, err := source.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = late.Rollback(ctx) }()
	if _, err = late.Exec(ctx, `UPDATE retired_accounts SET payload='{"late":true}' WHERE id=1`); err != nil {
		t.Fatal(err)
	}
	if _, err = source.Exec(ctx, `UPDATE parent SET amount=amount+1 WHERE id=1; UPDATE invoice_requests SET status='issued' WHERE id=1`); err != nil {
		t.Fatal(err)
	}
	var first bytes.Buffer
	if _, err = ExportOnlineDelta(ctx, source, opts.RunID, &first); err != nil {
		t.Fatal(err)
	}
	if _, err = ApplyOnlineDelta(ctx, target, &first, opts); err != nil {
		t.Fatal(err)
	}
	if err = late.Commit(ctx); err != nil {
		t.Fatal(err)
	}
	if _, err = source.Exec(ctx, `DELETE FROM child WHERE id=1; UPDATE parent SET id=3,payload='{"large":999999999999999999999999999999,"text":"changed"}' WHERE id=1; DELETE FROM parent WHERE id=2; INSERT INTO child VALUES(2,3); DELETE FROM notes; INSERT INTO notes VALUES('new'),('new'); SELECT setval('parent_id_seq',3,true)`); err != nil {
		t.Fatal(err)
	}
	if _, err = source.Exec(ctx, `INSERT INTO retired_accounts SELECT n,jsonb_build_object('n',n,'precise',999999999999999999999999999999::numeric) FROM generate_series(2,400)n; UPDATE parent SET payload=payload||jsonb_build_object('long',repeat('x',1048576)) WHERE id=3`); err != nil {
		t.Fatal(err)
	}
	// The full-delta consumer must retain acknowledged events.
	if _, err = source.Exec(ctx, `UPDATE v3_migration_capture.events SET acked=true`); err != nil {
		t.Fatal(err)
	}
	var delta bytes.Buffer
	manifest, err := ExportOnlineDelta(ctx, source, opts.RunID, &delta)
	if err != nil {
		t.Fatal(err)
	}
	want := onlineBackupDigest(t, source)
	for i := 0; i < 2; i++ {
		applied, e := ApplyOnlineDelta(ctx, target, bytes.NewReader(delta.Bytes()), opts)
		if e != nil {
			t.Fatal(e)
		}
		if applied.SHA256 != manifest.SHA256 || onlineBackupDigest(t, target) != want {
			t.Fatal("full fields or replay digest differ")
		}
	}
	var next int64
	if err = target.QueryRow(ctx, `SELECT nextval('parent_id_seq')`).Scan(&next); err != nil || next != 4 {
		t.Fatalf("sequence next value=%d err=%v", next, err)
	}
	if entries, e := os.ReadDir(opts.SpoolDirectory); e != nil || len(entries) != 0 {
		t.Fatal("spool not cleaned")
	}
}

func TestOnlineDeltaTransportAndTransactionFailures(t *testing.T) {
	ctx, source, target, opts := onlineBackupDBs(t)
	for _, pool := range []*pgxpool.Pool{source, target} {
		if _, err := pool.Exec(ctx, onlineBackupFixture); err != nil {
			t.Fatal(err)
		}
	}
	if _, err := SetupOnlineCapture(ctx, source, opts.RunID, true); err != nil {
		t.Fatal(err)
	}
	if _, err := source.Exec(ctx, `UPDATE parent SET amount=5 WHERE id=1; UPDATE notes SET body='changed'`); err != nil {
		t.Fatal(err)
	}
	var delta bytes.Buffer
	if _, err := ExportOnlineDelta(ctx, source, opts.RunID, &delta); err != nil {
		t.Fatal(err)
	}
	baseline := onlineBackupDigest(t, target)
	bad := append([]byte(nil), delta.Bytes()...)
	bad = bytes.Replace(bad, []byte(`"amount": 5.000000`), []byte(`"amount": 6.000000`), 1)
	if bytes.Equal(bad, delta.Bytes()) {
		bad[bytes.LastIndex(bad, []byte(`"sha256":"`))+10] = 'x'
	}
	cases := map[string][]byte{"checksum": bad, "missing-trailer": delta.Bytes()[:bytes.LastIndex(bytes.TrimSuffix(delta.Bytes(), []byte{'\n'}), []byte{'\n'})+1], "after-trailer": append(append([]byte(nil), delta.Bytes()...), []byte("{}\n")...)}
	for name, bundle := range cases {
		t.Run(name, func(t *testing.T) {
			if _, err := ApplyOnlineDelta(ctx, target, bytes.NewReader(bundle), opts); err == nil {
				t.Fatal("invalid bundle accepted")
			}
			if onlineBackupDigest(t, target) != baseline {
				t.Fatal("failed bundle changed data")
			}
		})
	}
	wrong := opts
	wrong.Database = "neondb"
	if _, err := ApplyOnlineDelta(ctx, target, bytes.NewReader(delta.Bytes()), wrong); err == nil {
		t.Fatal("production database name accepted")
	}
	wrong = opts
	wrong.Database = "online_restore_wrong"
	if _, err := ApplyOnlineDelta(ctx, target, bytes.NewReader(delta.Bytes()), wrong); err == nil {
		t.Fatal("wrong actual database accepted")
	}
	// Preserve a valid checksum but inject an invalid FK: failure occurs after
	// actual deletes/inserts and must roll the whole transaction back.
	corrupt := onlineRewriteDelta(t, delta.Bytes(), func(rec *onlineDeltaRecord) {
		if rec.Kind == "row" && rec.Table == "public.parent" {
			rec.Row = json.RawMessage(`{"id":1,"amount":null,"payload":{},"doubled":null}`)
		}
	})
	if _, err := ApplyOnlineDelta(ctx, target, bytes.NewReader(corrupt), opts); err == nil {
		t.Fatal("NOT NULL violation accepted")
	}
	if onlineBackupDigest(t, target) != baseline {
		t.Fatal("transaction failure did not roll back")
	}
	foreignKeyViolation := onlineRewriteDelta(t, delta.Bytes(), func(rec *onlineDeltaRecord) {
		if rec.Kind == "row" && rec.Table == "public.parent" {
			rec.Row = json.RawMessage(`{"id":99,"amount":5,"payload":{},"doubled":10}`)
		}
	})
	if _, err := ApplyOnlineDelta(ctx, target, bytes.NewReader(foreignKeyViolation), opts); err == nil {
		t.Fatal("orphaned unchanged child accepted")
	}
	if onlineBackupDigest(t, target) != baseline {
		t.Fatal("FK revalidation failure did not roll back")
	}
	// A later exhausted sequence must roll back an earlier ALTER RESTART, too.
	if _, err := source.Exec(ctx, `CREATE SEQUENCE z_exhausted MAXVALUE 10 START 10`); err != nil {
		t.Fatal(err)
	}
	if _, err := ExportOnlineDelta(ctx, source, opts.RunID, &bytes.Buffer{}); err != nil {
		t.Fatal(err)
	}
	if _, err := target.Exec(ctx, `CREATE SEQUENCE z_exhausted MAXVALUE 10 START 10`); err != nil {
		t.Fatal(err)
	}
	if _, err := source.Exec(ctx, `SELECT nextval('z_exhausted'); SELECT setval('parent_id_seq',8,true)`); err != nil {
		t.Fatal(err)
	}
	var exhausted bytes.Buffer
	if _, err := ExportOnlineDelta(ctx, source, opts.RunID, &exhausted); err != nil {
		t.Fatal(err)
	}
	if _, err := ApplyOnlineDelta(ctx, target, &exhausted, opts); err == nil {
		t.Fatal("exhausted sequence accepted")
	}
	var last int64
	var called bool
	if err := target.QueryRow(ctx, `SELECT last_value,is_called FROM parent_id_seq`).Scan(&last, &called); err != nil || last != 2 || !called {
		t.Fatalf("sequence rollback last=%d called=%v err=%v", last, called, err)
	}
	if onlineBackupDigest(t, target) != baseline {
		t.Fatal("sequence failure changed rows")
	}
}

func TestOnlineSequenceBoundarySemantics(t *testing.T) {
	for _, tc := range []struct {
		name string
		s    onlineSequence
		want int64
		fail bool
	}{
		{"not-called", onlineSequence{LastValue: 10, Minimum: 1, Maximum: 10, Increment: 1}, 10, false},
		{"exhausted", onlineSequence{LastValue: 10, Minimum: 1, Maximum: 10, Increment: 1, IsCalled: true}, 0, true},
		{"cycle-max", onlineSequence{LastValue: 10, Minimum: 1, Maximum: 10, Increment: 1, IsCalled: true, Cycle: true}, 1, false},
		{"cycle-min", onlineSequence{LastValue: -10, Minimum: -10, Maximum: -1, Increment: -1, IsCalled: true, Cycle: true}, -1, false},
		{"int64-max", onlineSequence{LastValue: math.MaxInt64, Minimum: 1, Maximum: math.MaxInt64, Increment: 1, IsCalled: true}, 0, true},
		{"int64-min", onlineSequence{LastValue: math.MinInt64, Minimum: math.MinInt64, Maximum: -1, Increment: -1, IsCalled: true, Cycle: true}, -1, false},
		{"negative-bound-positive-increment", onlineSequence{LastValue: math.MinInt64, Minimum: math.MinInt64, Maximum: math.MinInt64 + 1, Increment: math.MaxInt64, IsCalled: true, Cycle: true}, math.MinInt64, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := onlineSequenceNext(tc.s)
			if (err != nil) != tc.fail || (!tc.fail && got != tc.want) {
				t.Fatalf("got=%d err=%v want=%d fail=%v", got, err, tc.want, tc.fail)
			}
		})
	}
}

func TestOnlineDeltaPartitionMoveAndCompositeKey(t *testing.T) {
	ctx, source, target, opts := onlineBackupDBs(t)
	fixture := `CREATE TABLE owners(id bigint PRIMARY KEY); INSERT INTO owners VALUES(1);
 CREATE TABLE partitioned_rows(tenant bigint NOT NULL,id bigint NOT NULL,parent_id bigint NOT NULL REFERENCES owners(id),payload jsonb NOT NULL,PRIMARY KEY(tenant,id)) PARTITION BY RANGE(tenant);
 CREATE TABLE partitioned_low PARTITION OF partitioned_rows FOR VALUES FROM (0) TO (10);
 CREATE TABLE partitioned_high PARTITION OF partitioned_rows FOR VALUES FROM (10) TO (20);
 INSERT INTO partitioned_rows VALUES(1,1,1,'{"initial":true}');`
	for _, pool := range []*pgxpool.Pool{source, target} {
		if _, err := pool.Exec(ctx, fixture); err != nil {
			t.Fatal(err)
		}
	}
	if _, err := SetupOnlineCapture(ctx, source, opts.RunID, true); err != nil {
		t.Fatal(err)
	}
	if _, err := source.Exec(ctx, `UPDATE partitioned_rows SET tenant=11,payload='{"changed":99999999999999999999999999999}' WHERE tenant=1 AND id=1`); err != nil {
		t.Fatal(err)
	}
	var delta bytes.Buffer
	if _, err := ExportOnlineDelta(ctx, source, opts.RunID, &delta); err != nil {
		t.Fatal(err)
	}
	if _, err := ApplyOnlineDelta(ctx, target, &delta, opts); err != nil {
		t.Fatal(err)
	}
	var actual, want string
	query := `SELECT jsonb_agg(to_jsonb(t) ORDER BY tenant,id)::text FROM partitioned_rows t`
	if err := source.QueryRow(ctx, query).Scan(&want); err != nil {
		t.Fatal(err)
	}
	if err := target.QueryRow(ctx, query).Scan(&actual); err != nil {
		t.Fatal(err)
	}
	if actual != want {
		t.Fatal("composite primary-key partition move differs")
	}
}

func onlineRewriteDelta(t *testing.T, bundle []byte, change func(*onlineDeltaRecord)) []byte {
	t.Helper()
	var out bytes.Buffer
	h := sha256.New()
	var count int64
	for _, line := range bytes.Split(bytes.TrimSuffix(bundle, []byte{'\n'}), []byte{'\n'}) {
		var rec onlineDeltaRecord
		if err := json.Unmarshal(line, &rec); err != nil {
			t.Fatal(err)
		}
		if rec.Kind == "trailer" {
			rec.Records = count
			rec.SHA256 = hex.EncodeToString(h.Sum(nil))
		} else {
			change(&rec)
			count++
		}
		encoded, err := json.Marshal(rec)
		if err != nil {
			t.Fatal(err)
		}
		encoded = append(encoded, '\n')
		out.Write(encoded)
		if rec.Kind != "trailer" {
			h.Write(encoded)
		}
	}
	return out.Bytes()
}

func TestOnlineBaseBackupRealPGDumpAndDelta(t *testing.T) {
	if _, err := exec.LookPath("pg_dump"); err != nil {
		t.Skip("pg_dump not on PATH")
	}
	if _, err := exec.LookPath("pg_restore"); err != nil {
		t.Skip("pg_restore not on PATH")
	}
	ctx, source, target, opts := onlineBackupDBs(t)
	if _, err := source.Exec(ctx, onlineBackupFixture); err != nil {
		t.Fatal(err)
	}
	if _, err := SetupOnlineCapture(ctx, source, opts.RunID, true); err != nil {
		t.Fatal(err)
	}
	destination := filepath.Join(t.TempDir(), "base.dump")
	manifest, err := OnlineBaseBackup(ctx, source, opts.RunID, destination)
	if err != nil {
		t.Fatal(err)
	}
	if manifest.Bytes == 0 || len(manifest.SHA256) != 64 {
		t.Fatal("missing archive digest")
	}
	if _, err = OnlineBaseBackup(ctx, source, opts.RunID, destination); err == nil {
		t.Fatal("existing backup overwritten")
	}
	list, err := exec.CommandContext(ctx, "pg_restore", "--list", destination).Output()
	if err != nil {
		t.Fatal(err)
	}
	var filtered []string
	for _, line := range strings.Split(string(list), "\n") {
		exclude := false
		if strings.Contains(line, " TRIGGER ") {
			for _, name := range manifest.ExcludedTriggerNames {
				if strings.Contains(line, " "+name+" ") {
					exclude = true
				}
			}
		}
		if !exclude {
			filtered = append(filtered, line)
		}
	}
	listPath := filepath.Join(t.TempDir(), "restore.list")
	if err = os.WriteFile(listPath, []byte(strings.Join(filtered, "\n")), 0600); err != nil {
		t.Fatal(err)
	}
	dumpEnv, err := onlineDumpEnvironment(target.Config().ConnConfig)
	if err != nil {
		t.Fatal(err)
	}
	command := exec.CommandContext(ctx, "pg_restore", "--exit-on-error", "--use-list="+listPath, "--dbname="+opts.Database, destination)
	for _, entry := range os.Environ() {
		if !strings.HasPrefix(entry, "PG") {
			command.Env = append(command.Env, entry)
		}
	}
	command.Env = append(command.Env, dumpEnv...)
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("fixture restore failed: %v %s", err, output)
	}
	if onlineBackupDigest(t, target) != onlineBackupDigest(t, source) {
		t.Fatal("actual base archive differs")
	}
	if _, err = source.Exec(ctx, `UPDATE invoice_requests SET status='issued'; UPDATE parent SET amount=7 WHERE id=1; DELETE FROM notes; INSERT INTO notes VALUES('final')`); err != nil {
		t.Fatal(err)
	}
	var delta bytes.Buffer
	if _, err = ExportOnlineDelta(ctx, source, opts.RunID, &delta); err != nil {
		t.Fatal(err)
	}
	if _, err = ApplyOnlineDelta(ctx, target, &delta, opts); err != nil {
		t.Fatal(err)
	}
	if onlineBackupDigest(t, target) != onlineBackupDigest(t, source) {
		t.Fatal("restored archive plus final delta differs")
	}
}
