// Command generate writes the domain dispatch implementation of the generated
// OpenAPI interface. The business handlers stay in their own packages.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
)

func main() {
	if err := generate(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() error {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "server.gen.go", nil, 0)
	if err != nil {
		return err
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by api/generate. DO NOT EDIT.\npackage api\nimport \"net/http\"\n")
	count := 0
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range gen.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok || typeSpec.Name.Name != "ServerInterface" {
				continue
			}
			for _, field := range typeSpec.Type.(*ast.InterfaceType).Methods.List {
				method := field.Type.(*ast.FuncType)
				fmt.Fprintf(&output, "func (a *domainAdapter) %s", field.Names[0].Name)
				var params bytes.Buffer
				if err := printer.Fprint(&params, fset, method); err != nil {
					return err
				}
				output.Write(bytes.TrimPrefix(params.Bytes(), []byte("func")))
				output.WriteString(" { a.next.ServeHTTP(w, r) }\n")
				count++
			}
		}
	}
	if count == 0 {
		return fmt.Errorf("ServerInterface has no methods")
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile("dispatch.gen.go", formatted, 0644)
}
